module.exports = {
    "About us" : "About us",
    "About" : "About",
    "Activity" : "Activity",
    "Add bot" : "Add bot",
    "Add comment" : "Add comment",
    "Add link" : "Add link",
    "Add picture" : "Add picture",
    "Add tags" : "Add tags",
    "Add text" : "Add text",
    "Add Video" : "Add Video",
    "Add_link_bot" : "Link to JavaScript file or npm package name.",
    "Add" : "Add",
    "Added" : "Added",
    "ago" : "ago",
    "and" : "and",
    "Anonymous post" : "Anonymous post",
    "Anonymous Post" : "Anonymous Post",
    "Anonymous_post_long" : "Don't forget to copy the link to your anonymous post. This post cannot be deleted as long as you or at least one other person keeps this link. If nobody has a link to this post, this post will be lost forever. ",
    "Anyone can post into this stream" : "Anyone can post into this stream",
    "Attributes" : "Attributes",
    "Best" : "Best",
    "Blog" : "Blog",
    "Board name" : "Board name",
    "Bots" : "Bots",
    "by" : "by",
    "Card" : "Card",
    "Change password" : "Change password",
    "change_password_txt" : "Want to change your password? We will send you a password reset e-mail.",
    "Choose_image" : "Choose image\u2026",
    "Code" : "Code",
    "Color" : "Color",
    "Company" : "Company",
    "Connect with" : "Connect with",
    "Connect" : "Connect",
    "Copied" : "Copied",
    "Copy link" : "Copy link",
    "Copy" : "Copy",
    "Create a post" : "Create a post",
    "Create stream" : "Create stream",
    "create_first_post" : "Create your first post.",
    "Create" : "Create",
    "Created" : "Created",
    "day" : "day",
    "days" : "days",
    "Default: Latest first" : "Default: Latest first",
    "Delete forever" : "Delete forever",
    "Delete stream" : "Delete stream",
    "Delete this post forever" : "Delete this post forever",
    "Delete this stream forever" : "Delete this stream forever",
    "Delete_post" : "Are you sure you want to delete this post?",
    "Delete_stream_note" : "Note that by deleting this stream your individual posts will not be removed. You can delete your posts by accessing their links.",
    "Delete_stream" : "Are you sure you want to delete this stream? This cannot be undone.",
    "Delete" : "Delete",
    "Deleted" : "Deleted",
    "Description" : "Description",
    "Develop" : "Develop",
    "Developer Console" : "Developer Console",
    "Diff" : "Diff",
    "Disconnect" : "Disconnect",
    "Discussion" : "Discussion",
    "Done" : "Done",
    "Down votes" : "Down votes",
    "Downs" : "Downs",
    "Drag_drop" : "Drag & drop image here",
    "Drop" : "Drop",
    "E-mail" : "E-mail",
    "Edit_me" : "Edit me\u2026",
    "Edit your post below:" : "Edit your post below:",
    "Edit" : "Edit",
    "Embed on your site" : "Embed on your site",
    "Embed" : "Embed",
    "Enter web link to your image" : "Enter web link to your image",
    "Enter web page to fetch" : "Enter web page to fetch",
    "Error" : "Error",
    "Explore" : "Explore",
    "Filter author posts" : "Filter author posts",
    "Filter" : "Filter",
    "Finish" : "Finish",
    "first_post" : "No posts yet. Create your first post.",
    "Follow" : "Follow",
    "Followers" : "Followers",
    "Following" : "Following",
    "Font" : "Font",
    "Fonts" : "Fonts",
    "Forgot password" : "Forgot password",
    "Forgot_password" : "Forgot your password? We will send you an e-mail to reset your password.",
    "Fork this post" : "Fork this post",
    "Fork" : "Fork",
    "General" : "General",
    "Go to post" : "Go to post",
    "Highest rated first" : "Highest rated first",
    "Highest rated" : "Highest rated",
    "History": "History",
    "Hot first" : "Hot first",
    "Hot" : "Hot",
    "hour" : "hour",
    "hours" : "hours",
    "ID" : "ID",
    "Images" : "Images",
    "in" : "in",
    "In" : "In",
    "Info" : "Info",
    "Install" : "Install",
    "Joined" : "Joined",
    "Karma" : "Karma",
    "Language" : "Language",
    "Latest first" : "Latest first",
    "Latest" : "Latest",
    "Learn about bots" : "Learn about bots",
    "Learn more about anonymous posts" : "Learn more about anonymous posts",
    "Learn more" : "Learn more",
    "Less" : "Less",
    "Link to image" : "Link to image",
    "Link to video" : "Link to video",
    "Link to YouTube video" : "Link to YouTube video",
    "Link" : "Link",
    "Load more" : "Load more",
    "Login" : "Login",
    "Logout" : "Logout",
    "Manage bots" : "Manage bots",
    "Manifest" : "Manifest",
    "Mark_nudity" : "Mark this content as containing nudity, pornography or other mature or explicit content.",
    "Markdown Help" : "Markdown Help",
    "Markdown" : "Markdown",
    "minute" : "minute",
    "minutes" : "minutes",
    "Moderators" : "Moderators",
    "Modified" : "Modified",
    "month" : "month",
    "months" : "months",
    "More pictures" : "More pictures",
    "More streams" : "More streams",
    "more" : "more",
    "More" : "More",
    "My P's" : "Мy P's",
    "My Posts" : "My Posts",
    "My streams" : "My streams",
    "My Streams" : "My Streams",
    "Name" : "Name",
    "New board" : "New board",
    "New bot" : "New bot",
    "New Post" : "New Post",
    "New post" : "New post",
    "No_bots" : "You do not have any bots connected yet.",
    "no_posts_yet" : "No posts here, yet.",
    "Oldest first" : "Oldest first",
    "Oldest" : "Oldest",
    "Only you and moderators can post into this stream" : "Only you and moderators can post into this stream",
    "Optional" : "Optional",
    "or drag image here" : "or drag image here",
    "P4 Components" : "P4 Components",
    "P4 Product" : "P4 Product",
    "Package" : "Package",
    "Password" : "Password",
    "Paste image with" : "Paste image with",
    "Paste" : "Paste",
    "Permissions" : "Permissions" ,
    "Pick a file" : "Pick a file\u2026",
    "Pick file from your hard drive" : "Pick file from your hard drive",
    "Picked streams" : "Picked streams",
    "Post something" : "Post something",
    "Post_anonymously" : "DON'T WANT TO SIGN IN? POST ANONYMOUSLY",
    "Post_count" : "Posts",
    "Post_fork" : "Select streams where to post your fork",
    "Post" : "Post",
    "Posts" : "Posts",
    "Powered by" : "Powered by",
    "Preview" : "Preview",
    "Privacy Policy" : "Privacy Policy" ,
    "Privacy" : "Privacy",
    "Private" : "Private",
    "Profile" : "Profile",
    "Publish" : "Publish",
    "Rating" : "Rating",
    "Re-enter" : "Re-enter",
    "Read-only" : "Read-only",
    "Report abuse" : "Report abuse",
    "Report Bugs" : "Report Bugs",
    "Report this post" : "Report this post",
    "Report_post" : "Reported posts are reviewed daily to determine if they violate our Terms of Use. Accounts violating our Terms of Use may be terminated.",
    "Report" : "Report",
    "Reset password" : "Reset password",
    "reset_code" : "Reset code has been sent to your e-mail, type it here with your new password.",
    "Saved" : "Saved",
    "Search" : "Search",
    "seconds" : "seconds",
    "Security" : "Security",
    "See more streams" : "See more streams",
    "Select default font style for your posts" : "Select default font style for your posts",
    "Select Image" : "Select Image",
    "Send e-mail" : "Send e-mail",
    "Send" : "Send",
    "Settings" : "Settings",
    "Share on" : "Share on",
    "Share" : "Share",
    "Short Link" : "Short Link",
    "Short link" : "Short link",
    "Shorten Link" : "Shorten Link",
    "Sign up" : "Sign up",
    "Sign_with_pseudonym" : "Optionally, sign the post with pseudonym or avatar",
    "Slug" : "Slug",
    "Social" : "Social",
    "Sorting" : "Sorting",
    "Source" : "Source",
    "Start posting right now" : "Start posting right now",
    "Stream name" : "Stream name",
    "Stream" : "Stream",
    "Streams" : "Streams",
    "Styles" : "Styles",
    "Submit" : "Submit",
    "Tags" : "Tags",
    "Terms of Use" : "Terms of Use",
    "terms" : "terms",
    "This is your post" : "This is your post",
    "This stream is private, only you and moderators can see it" : "This stream is private, only you and moderators can see it",
    "This stream is public, anyone can see it" : "This stream is public, anyone can see it",
    "Thumbnail" : "Thumbnail",
    "Tip" : "Tip",
    "Title" : "Title",
    "Trending first" : "Trending first",
    "Trending Posts" : "Trending Posts",
    "Trending" : "Trending",
    "try_again" : "Oops! Error, please try again later.",
    "Type reply" : "Type reply",
    "Unfollow" : "Unfollow",
    "Unknown" : "Unknown",
    "Unnamed" : "Unnamed",
    "Up votes" : "Up votes",
    "Upload" : "Upload",
    "Ups" : "Ups",
    "User" : "Name",
    "Username" : "Username",
    "Videos" : "Videos",
    "View source" : "View source",
    "View" : "View",
    "Views" : "Views",
    "Visit" : "Visit",
    "Want to disconnect?" : "Want to disconnect? See, ya!",
    "Webhooks" : "Webhooks",
    "Worst" : "Worst",
    "years" : "years",
    "Your name" : "Your name",
    "Your Streams" : "Your Streams",
};
