module.exports = {
    Italic: 'Italic',
    text: 'text',
    Bold: 'Bold',
    Link: 'Link',
    Highlighted: 'Highlighted',
    Strikethrough: 'Strikethrough',
    Underlined: 'Underlined',
    Super: 'Super',
    Emoji: 'Emoji',
    Inline: 'Inline',
    tag: 'tag',
    Heading: 'Heading',
    Subheading: 'Subheading',
    puss: 'puss',
    'This is a block quote': 'This is a block quote',
    Item: 'Item',
    code: 'code',
    Bill: 'Bill',
    Bob: 'Bob',
    'Hello there': 'Hello there',
    Thinking: 'Thinking',
    Hello: 'Hello',
    BACK: 'BACK',
    Blocks: 'Blocks',
    Text: 'Text',
};
