module.exports = {
    Default: 'Default',
    'Latest first': 'Latest first',
    'Hot first': 'Hot first',
    'Trending first': 'Trending first',
    'Highest rated first': 'Highest rated first',
    'Oldest first': 'Oldest first',
    'This user is already a moderator': 'This user is already a moderator',
    'You cannot add yourself as moderator': 'You cannot add yourself as moderator',
    'Could not add moderator': 'Could not add moderator',
    Private: 'Private',
    'This stream is private, only you and moderators can see it':
        'This stream is private, only you and moderators can see it',
    'This stream is public, anyone can see it': 'This stream is public, anyone can see it',
    'Read-only': 'Read-only',
    'Only you and moderators can post into this stream': 'Only you and moderators can post into this stream',
    'Anyone can post into this stream': 'Anyone can post into this stream',
    Sorting: 'Sorting',
    View: 'View',
    Moderators: 'Moderators',
};
