module.exports = {

"About us" : "关于我们",
"About yourself\u2026" : "关于你自己\u2026"
"About" : "关于",
"Activity" : "活动",
"Add bot" : "添加程序",
"Add comment" : "添加评论",
"Add link" : "添加链接",
"Add picture" : "添加图片",
"Add tags" : "添加标签",
"Add text" : "添加文字",
"Add Video" : "添加视频",
"Add_link_bot" : "链接到JavaScript文件或npm包名称.",
"Add" : "添加",
"Added" : "已添加",
"ago" : "前",
"and" : "和",
"Anonymous post" : "匿名帖子",
"Anonymous Post" : "匿名帖子",
"Anonymous_post_long" : "不要忘记将链接复制到您的匿名帖子。只要您或至少一人保留此链接，此帖子就无法删除。如果没有任何人有此帖子的链接，此帖子将永久丢失. ",
"Anyone can post into this stream" : "任何人都可以发布到此话题",
"Attributes" : "属性",
"Best" : "最好的",
"Blog" : "博客",
"Board name" : "董事会名称",
"Bots" : "程序",
"by" : "通过",
"Card" : "卡",
"Change password" : "更改密码",
"change_password_txt" : "想要更改密码？我们将会向您发送密码重置邮件.",
"Choose_image" : "选择图像\u2026",
"Code" : "代码",
"Color" : "颜色",
"Company" : "公司",
"Connect with" : "连接",
"Connect" : "连接",
"Copied" : "已复制",
"Copy link" : "复制链接",
"Copy" : "复制",
"Create a post" : "创建帖子",
"Create stream" : "创建话题",
"create_first_post" : "创建您的第一篇帖子.",
"Create" : "创建",
"Created" : "已创建",
"day" : "天",
"days" : "天",
"Default: Latest first" : "默认：时间由近及远",
"Delete forever" : "永久删除",
"Delete stream" : "删除分支",
"Delete this post forever" : "永久删除这篇帖子",
"Delete this stream forever" : "永远删除此话题",
"Delete_post" : "您确定要删除此帖吗?",
"Delete_stream_note" : "请注意，通过删除此话题，您话题中的帖子不会被删除。您可以通过访问帖子的链接来删除帖子.",
"Delete_stream" : "您确定要删除此话题吗？删除后无法复原.",
"Delete" : "删除",
"Deleted" : "已删除",
"Description" : "描述",
"Develop" : "开发",
"Developer Console" : "开发人员控制台",
"Diff" : "区别",
"Disconnect" : "断开连接",
"Discussion" : "讨论",
"Done" : "完成",
"Down votes" : "踩",
"Downs" : "踩",
"Drag_drop" : "拖放图像",
"Drop" : "“放下",
"E-mail" : "电子邮件",
"Edit tags" : "修改标签"
"Edit your post below:" : "在下方编辑您的帖子:",
"Edit_me" : "编辑我\u2026",
"Edit" : "编辑",
"Embed on your site" : "嵌入您的网站",
"Embed" : "嵌入",
"Enter web link to your image" : "输入图片的网页链接",
"Enter web page to fetch" : "输入要获取的网页",
"Error" : "错误",
"Explore" : "发现",
"Feedback" : "意见反馈",
"Filter author posts" : "筛选作者帖子",
"Filter" : "筛选",
"Finish" : "完成",
"first_post" : "还没有帖子。创建你的第一篇帖子.",
"Follow" : "关注",
"Followers" : "粉丝",
"Following" : "关注",
"Font" : "字体",
"Fonts" : "字体",
"Forgot password" : "忘记密码",
"Forgot_password" : "忘记密码？我们将会向您发送一封电子邮件以重置您的密码.",
"Fork this post" : "转发本帖",
"Fork" : "转帖",
"General" : "通用",
"Go to post" : "前往帖子",
"Highest rated first" : "评分最高优先",
"Highest rated" : "评分最高",
"History": "历史",
"Hot first" : "热门第一",
"Hot" : "热门",
"hour" : "小时",
"hours" : "小时",
"ID" : "ID",
"Images" : "图片",
"in" : "在",
"In" : "在",
"Info" : "信息",
"Install" : "安装",
"Joined" : "已加入",
"Karma" : "等级",
"Language" : "语言",
"Latest first" : "时间最近优先",
"Latest" : "最新",
"Learn about bots" : "了解程序",
"Learn more about anonymous posts" : "了解有关匿名帖子的详情",
"Learn more" : "了解更多",
"Leave your comment" : "留下您的评论",
"Less" : "少",
"Link to image" : "链接到图像",
"Link to video" : "链接到视频",
"Link to YouTube video" : "链接到YouTube视频",
"Link" : "链接",
"Load more" : "加载更多",
"Login" : "登录",
"Logout" : "退出",
"Manage bots" : "管理程序",
"Manifest" : "显示",
"Mark_nudity" : "将此内容标记为包含裸露，色情或其他少儿不宜、暴露的内容.",
"Markdown Help" : "Markdown帮助",
"Markdown" : "Markdown",
"minute" : "分钟",
"minutes" : "分钟",
"Moderators" : "管理员",
"Modified" : "已修改",
"month" : "月",
"months" : "月",
"More pictures" : "更多图片",
"More streams" : "更多话题",
"more" : "更多",
"More" : "更多",
"My P's" : "我的帖子",
"My Posts" : "我的帖子",
"My streams" : "我的话题",
"My Streams" : "我的话题",
"Name" : "姓名",
"New board" : "新板",
"New bot" : "新的程序",
"New Post" : "新帖",
"New post" : "新帖",
"No_bots" : "您还没有连接任何程序.",
"no_posts_yet" : "此处没有帖子.",
"Oldest first" : "时间最远优先",
"Oldest" : "最早的",
"Only you and moderators can post into this stream" : "只有您和管理员可以发帖到这个话题",
"Optional" : "选填",
"or drag image here" : "或将图片拖动至此",
"P4 Components" : "P4组件",
"P4 Product" : "P4产品",
"Package" : "套餐",
"Password" : "密码",
"Paste image or link" : "粘贴图片或链接",
"Paste image with" : "粘贴图像",
"Paste" : "粘贴",
"Permissions" : "权限" ,
"Pick a file" : "选择一个文件\u2026",
"Pick file from your hard drive" : "从硬盘中选择文件",
"Picked streams" : "已选话题",
"Post on Enter" : "按输入键发布",
"Post something" : "发布",
"Post_anonymously" : "不想登录？匿名发布",
"Post_count" : "帖子",
"Post_fork" : "选择要发布转帖的话题",
"Post" : "帖子",
"Posts" : "帖子",
"Powered by" : "供电",
"Preview" : "预览",
"Privacy Policy" : "隐私政策" ,
"Privacy" : "隐私",
"Private" : "私人",
"Profile" : "个人资料",
"Publish" : "发布",
"Rating" : "评级",
"Re-enter" : "重新输入",
"Read-only" : "只读",
"Report abuse" : "举报滥用行为",
"Report Bugs" : "报告错误",
"Report this post" : "举报此帖",
"Report_post" : "我们每天都会审核被举报的帖子，以确定它们是否违反了我们的使用条款。违反使用条款的帐户可能会被终止.",
"Report" : "举报",
"Reset password" : "重置密码",
"reset_code" : "重置密码已发送到您的电子邮箱，请使用新密码在此处键入.",
"Saved" : "已保存",
"Search" : "搜索",
"seconds" : "秒",
"Security" : "安全保护",
"See more streams" : "查看更多话题",
"Select default font style for your posts" : "为帖子选择默认字体样式",
"Select Image" : "选择图片",
"Select image" : "选择图片",
"Select streams where to post your fork" : "选择要发布转帖的话题",
"Send e-mail" : "发送电子邮件",
"Send" : "发送",
"Settings" : "设置",
"Share on" : "分享在",
"Share" : "分享",
"Short Link" : "短链接",
"Short link" : "短链接",
"Shorten Link" : "缩短链接",
"Sign up" : "注册",
"Sign_with_pseudonym" : "可选择使用假名或头像发布帖子",
"Slug" : "URL地址",
"Social" : "社交",
"Sorting" : "分类",
"Source" : "来源",
"Start posting right now" : "立即开始发布",
"Stream name" : "话题名称",
"Stream" : "话题",
"Streams" : "话题",
"Style" : "风格",
"Styles" : "风格",
"Submit" : "提交",
"Tags" : "标签",
"Terms of Use" : "使用条款",
"terms" : "条款",
"This is your post" : "这是您的帖子",
"This stream is private, only you and moderators can see it" : "此话题是私人的，只有您和管理员可以看到它",
"This stream is public, anyone can see it" : "此话题是公开的，任何人都可以看到它",
"Thumbnail" : "缩略图",
"Tip" : "提示",
"Title" : "标题",
"Trending first" : "按受欢迎趋势排序";
"Trending Posts" : "受欢迎的帖子",
"Trending" : "受欢迎",
"try_again" : "哎呀！错误，请稍后再试.",
"Type reply" : "输入回复",
"Unfollow" : "取消关注",
"Unknown" : "未知",
"Unnamed" : "未命名",
"Up votes" : "赞",
"Upload" : "上传",
"Ups" : "赞",
"User" : "用户",
"Username" : "用户名",
"Videos" : "视频",
"View source" : "查看来源",
"View" : "浏览",
"Views" : "浏览",
"Visit" : "访问",
"Want to disconnect?" : "想断开连接？后会有期！",
"Webhooks" : "Webhooks",
"Worst" : "最糟糕",
"years" : "年",
"Your name" : "您的姓名",
"Your Streams" : "您的话题",
};
