module.exports = {
"Italic": "斜体",
"text": "文本",
"Bold": "粗体",
"Link" : "链接",
"Highlighted" : "已突出显示",
"Strikethrough" : "删除线",
"Underlined" : "加下划线",
"Super" : "超级",
"Emoji" : "表情符号”",
"Inline" : "内联",
"tag" : "标签",
"Heading" : "标题",
"Subheading" : "小标题",
"cat" : "猫",
"This is a block quote" : "这是一个区块引用",
"Item" : "项目",
"code" : "代码",
"Bill" : "张三",
"Bob" : "李四",
"Hello there" : "您好",
"Thinking" : "考虑中",
"Hello" : "你好",
"BACK" : "返回",
"Blocks" : "区块",
"Text" : "文本",
};
