module.exports = {
    "About us" : "Über uns",
    "About" : "Über",
    "Activity" : "Aktivität",
    "Add bot" : "Bote hinzufügen",
    "Add comment" : "Kommentar hinzufügen",
    "Add link" : "Link hinzufügen",
    "Add picture" : "Bild hinzufügen",
    "Add tags" : "Tags hinzufügen",
    "Add text" : "Text hinzufügen",
    "Add Video" : "Video hinzufügen",
    "Add_link_bot" : "Link zu JavaScript Feile oder npm Paket Name",
    "Add" : "Hinzufügen",
    "Added" : "Hinzugefügt",
    "ago" : "vor",
    "and" : "und",
    "Anonymous post" : "Anonymer post",
    "Anonymous Post" : "Anonymer Post",
    "Anonymous_post_long" : "Vergessen Sie nicht, den Link zu Ihrem anonymen Post zu kopieren. Dieser Post kann nicht gelöscht werden, solange du oder mindestens eine andere Person diesen Link behält. Wenn niemand einen Link zu diesem Post hat, wird dieser Post für immer verloren gehen. ",
    "Anyone can post into this stream" : "Jeder kann in diesen Strom posten",
    "Attributes" : "Attribute",
    "Best" : "Beste",
    "Blog" : "Blog",
    "Board name" : "Boardsname",
    "Bots" : "Boten",
    "by" : "durch",
    "Card" : "Karte",
    "Change password" : "Passwort ändern",
    "change_password_txt" : "Wollen Sie Ihr Passwort ändern? Wir schicken Ihnen ein Passwort zurücksetzen E-Mail.",
    "Choose_image" : "Wähle das Bild\u2026",
    "Code" : "Code",
    "Color" : "Farbe",
    "Company" : "Kompanie",
    "Connect with" : "Verbinden met",
    "Connect" : "Verbinden",
    "Copied" : "Kopiert",
    "Copy link" : "Link kopieren",
    "Copy" : "Kopieren",
    "Create a post" : "Post erstellen",
    "Create stream" : "Strom erstellen",
    "create_first_post" : "Erstellen Sie Ihren ersten Post.",
    "Create" : "Erstellen",
    "Created" : "Erstellt",
    "day" : "Tag",
    "days" : "Tagen",
    "Default: Latest first" : "Default: Neueste zuerst",
    "Delete forever" : "Für immer löschen",
    "Delete stream" : "Strom löschen",
    "Delete this post forever" : "Diesen Post für immer löschen",
    "Delete this stream forever" : "Diesen Strom für immer löschen ",
    "Delete_post" : "Sind Sie sicher, dass Sie diesen Post löschen möchten?",
    "Delete_stream_note" : "Beachten Sie, dass durch das Löschen dieses Strom Ihre einzelnen Post nicht entfernt werden. Sie können Ihre Post durch den Zugriff auf ihre Links löschen.",
    "Delete_stream" : "Sind Sie sicher, dass Sie diesen Strom löschen möchten? Das kann nicht rückgängig gemacht werden.",
    "Delete" : "Löschen",
    "Deleted" : "Gelöscht",
    "Description" : "Beschreibung",
    "Develop" : "Entwickeln",
    "Developer Console" : "Entwickler Konsole",
    "Diff" : "Diff",
    "Disconnect" : "Trennen",
    "Discussion" : "Diskussion",
    "Done" : "Erledigt",
    "Down votes" : "Daumen runter",
    "Downs" : "Unten",
    "Drag_drop" : "Ziehen und Ablegen ein Bild hier",
    "Drop" : "Ablegen",
    "E-mail" : "E-mail",
    "Edit_me" : "Bearbeiten mich\u2026",
    "Edit your post below:" : "Bearbeiten Sie Ihren Post unten:",
    "Edit" : " Bearbeiten",
    "Embed on your site" : "Einbetten auf Ihrer Webseite",
    "Embed" : "Einbetten",
    "Enter web link to your image" : "Link zu Ihrem Bild eingeben",
    "Enter web page to fetch" : "Geben Sie Webseite zu holen",
    "Error" : "Fehler",
    "Explore" : "Erforschen",
    "Filter author posts" : "Filter Autor Posten",
    "Filter" : "Filter",
    "Finish" : "Fertig",
    "first_post" : "Keine Posten noch. Erstellen Sie Ihren ersten Post.",
    "Follow" : "Folgen",
    "Followers" : "Nachfolger",
    "Following" : "Nachfolgend",
    "Font" : "Schriftart",
    "Fonts" : "Schriftarten",
    "Forgot password" : "Passwort vergessen",
    "Forgot_password" : "Haben Sie Ihr Passwort vergessen? Wir schicken Ihnen eine E-Mail, um Ihr Passwort zurückzusetzen.",
    "Fork this post" : "Forken diesen Post",
    "Fork" : "Forken",
    "General" : "Allgemein",
    "Go to post" : "Gehen Sie zum Post",
    "Highest rated first" : "Highest rated zuerst",
    "Highest rated" : "Höchstbewertet",
    "History": "Geschichte",
    "Hot first" : "Heiss zuerst",
    "Hot" : "Heiss",
    "hour" : "Stunde",
    "hours" : "Stunden",
    "ID" : "ID",
    "Images" : "Bilden",
    "in" : "im",
    "In" : "Im",
    "Info" : "Info",
    "Install" : "Installieren",
    "Joined" : "Beigetreten",
    "Karma" : "Karma",
    "Language" : "Sprache",
    "Latest first" : "Neueste zuerst",
    "Latest" : "Neueste",
    "Learn about bots" : "Erfahren Sie mehr über Boten",
    "Learn more about anonymous posts" : "Erfahren Sie mehr über anonyme Posten",
    "Learn more" : "Erfahren mehr",
    "Less" : "Weniger",
    "Link to image" : "Link zum Bild",
    "Link to video" : "Link zum Video",
    "Link to YouTube video" : "Link zum YouTube video",
    "Link" : "Link",
    "Load more" : "Mehr laden",
    "Login" : "Anmeldung",
    "Logout" : "Ausloggen",
    "Manage bots" : "Boten verwalten",
    "Manifest" : "Manifest",
    "Mark_nudity" : "Markiere diesen Inhalt als Nacktheit, Pornographie oder andere reife oder explizite Inhalte.",
    "Markdown Help" : "Markdown Hilfe",
    "Markdown" : "Markdown",
    "minute" : "Minute",
    "minutes" : "Minuten",
    "Moderators" : "Moderatoren",
    "Modified" : "Geändert",
    "month" : "Monat",
    "months" : "Monate",
    "More pictures" : "Mehr Bilder",
    "More streams" : "Mehr Ströme",
    "more" : "mehr",
    "More" : "Mehr",
    "My P's" : "Мeine Posten",
    "My Posts" : "Meine Posten",
    "My Streams" : "Meine Ströme",
    "My streams" : "Meine Ströme",
    "Name" : "Name",
    "New board" : "Neu Board",
    "New bot" : "Neuer Bot",
    "New Post" : "Neuer Post",
    "New post" : "Neuer Post",
    "No_bots" : "Sie haben noch keine Boten.",
    "no_posts_yet" : "Keine Posten hier, noch.",
    "Oldest first" : "Älteste zuerst",
    "Oldest" : "Älteste",
    "Only you and moderators can post into this stream" : "Nur Sie und Moderatoren können in diesen Strom einsteigen",
    "Optional" : "Optional",
    "or drag image here" : "oder zieh das Bild hier",
    "P4 Components" : "P4 Komponenten",
    "P4 Product" : "P4 Produkt",
    "Package" : "Paket",
    "Password" : "Passwort",
    "Paste image with" : "Einfügen ein Bild mit",
    "Paste" : "Einfügen",
    "Permissions" : "Berechtigungen" ,
    "Pick a file" : "Wählen Sie eine Feile\u2026",
    "Pick file from your hard drive" : "Von Festplatte auswählen",
    "Picked streams" : "Gepflückte Ströme",
    "Post something" : "Etwas posten",
    "Post_anonymously" : "NICHT WOLLEN SIE ZU ZEICHEN? POST ANONYM",
    "Post_count" : "Posten",
    "Post_fork" : "Wählen Sie Ströme, wo Sie Ihre Fork posten",
    "Post" : "Post",
    "Posts" : "Posten",
    "Powered" : "Unterstützt von",
    "Preview" : "Vorschau",
    "Privacy Policy" : "Datenschutzbestimmungen" ,
    "Privacy" : "Privatsphäre",
    "Private" : "Privat",
    "Profile" : "Profil",
    "Publish" : "Publizieren",
    "Rating" : "Bewertung",
    "Re-enter" : "Erneut eingeben",
    "Read-only" : "Read-only",
    "Report abuse" : "Missbrauch melden",
    "Report Bugs" : "Fehler melden",
    "Report this post" : "Diesen Post melden",
    "Report_post" : "Berichtete Posten werden täglich überprüft, um festzustellen, ob sie gegen unsere Nutzungsbedingungen verstoßen. Konten, die unsere Nutzungsbedingungen verletzen, können gekündigt werden.",
    "Report" : "Melden",
    "Reset password" : "Passwort zurücksetzen",
    "reset_code" : "Reset eine Code wurde an deine E-Mail gesendet, gib es hier mit deinem neuen Passwort ein.",
    "Saved" : "Gespeichert",
    "Search" : "Suche",
    "seconds" : "Sekunden",
    "Security" : "Sicherheit",
    "See more streams" : "Sehen Sie mehr Ströme",
    "Select default font style for your posts" : "Wählen Sie standard Schriftart für Ihre Posten",
    "Select Image" : "Bild Auswählen",
    "Send e-mail" : "E-mail senden",
    "Send" : "Senden",
    "Settings" : "Einstellungen",
    "Share on" : "Teilen auf",
    "Share" : "Tellen",
    "Short Link" : "Kurzlink",
    "Short link" : "Kurzlink",
    "Shorten Link" : "Link Verkürzen",
    "Sign up" : "Anmelden",
    "Sign_with_pseudonym" : "Optional, unterschreiben Sie den Post mit Pseudonym oder Avatar",
    "Slug" : "Link",
    "Social" : "Sozial",
    "Sorting" : "Sortierung",
    "Source" : "Quelle",
    "Start posting right now" : "Starten Sie posten sofort",
    "Stream name" : "Strom Name",
    "Stream" : "Strom",
    "Streams" : "Ströme",
    "Styles" : "Stile",
    "Submit" : "Einreichen",
    "Tags" : "Tags",
    "Terms of Use" : "Nutzungsbedingungen",
    "terms" : "Bedingungen",
    "This is your post" : "Das ist Sier Post",
    "This stream is private, only you and moderators can see it" : "Dieser Stream ist privat, nur Sie und Moderatoren können es sehen",
    "This stream is public, anyone can see it" : "Dieser Strom ist öffentlich, jeder kann es sehen",
    "Thumbnail" : "Miniaturansicht",
    "Tip" : "Tipp",
    "Title" : "Titel",
    "Trending first" : "Trending zuerst",
    "Trending Posts" : "Trendige Posten",
    "Trending" : "Trendige",
    "try_again" : "Fehler, bitte versuchen Sie es später noch einmal.",
    "Type reply" : "Antwort schreiben",
    "Unfollow" : "Aufhören zu folgen",
    "Unknown" : "Unbekannt",
    "Unnamed" : "Unbenannt",
    "Up votes" : "Daumen hoch",
    "Upload" : "Laden",
    "Ups" : "Oben",
    "User" : "Benutzer",
    "Username" : "Benutzername",
    "Videos" : "Videos",
    "View source" : "Um die Quelle anzuzeigen",
    "View" : "Sehen",
    "Views" : "Ansichten",
    "Visit" : "Besuch",
    "Want to disconnect?" : "Möchten Sie die Verbindung trennen?",
    "Webhooks" : "Webhooks",
    "Worst" : "Schlechteste",
    "years" : "Jahre",
    "Your name" : "Sier Name",
    "Your Streams" : "Siere Ströme",
};
