module.exports = {
    "Italic" : "Kursiv",
    "text": "Text",
    "Bold" : "Fett gedruckt",
    "Link" : "Link",
    "Highlighted" : "Hervorgehoben",
    "Strikethrough" : "Durchgestrichen",
    "Underlined" : "Unterstrichen",
    "Super": "Super",
    "Emoji" : "Emoji",
    "Inline": "In der Reihe",
    "tag": "hashtag",
    "Heading": "Titel",
    "Subheading": "Untertitel",
    "puss" : "Katze",
    "This is a block quote": "Dies ist ein Block Zitat",
    "Item": "Listenpunkt",
    "code": "code",
    "Bill": "Angela",
    "Bob": "Felix",
    "Hello there": "Hallo da",
    "Thinking": "Denken",
    "Hello": "Hallo",
    "BACK": "ZURÜCK",
    "Blocks" : "Blöcke",
    "Text": "Text",
};
