module.exports = {
    "About us" : "私たちについて",
    "About yourself\u2026" : "ご自分について\u2026"
    "About" : "約",
    "Activity" : "活動",
    "Add bot" : "ボットを追加する",
    "Add comment" : "コメントする",
    "Add link" : "リンクを追加する",
    "Add picture" : "写真を追加する",
    "Add tags" : "タグを追加する",
    "Add text" : "テキストを追加する",
    "Add Video" : "ビデオを追加する",
    "Add_link_bot" : "JavaScriptファイルまたはnpmパッケージ名にリンクします.",
    "Add" : "追加する",
    "Added" : "追加されました",
    "ago" : "前",
    "and" : "と",
    "Anonymous post" : "匿名投稿",
    "Anonymous Post" : "匿名投稿",
    "Anonymous_post_long" : "ご自分の匿名投稿へのリンクをコピーすることを忘れないでください。少なくとも１人がこのリンクを保持している限り、この投稿は削除されません。ただし、リンクが失われた場合、この投稿は永遠に消されます",
    "Anyone can post into this stream" : "誰でもこのストリームに投稿できます",
    "Attributes" : "特性",
    "Best" : "ベスト",
    "Blog" : "ブログ",
    "Board name" : "板名",
    "Bots" : "ボット",
    "by" : "から",
    "Card" : "カード",
    "Change password" : "パスワード変更する",
    "change_password_txt" : "パスワードを変更されたいですか？パスワードリセットのEメールを送信します.",
    "Choose_image" : "画像を選択する/u2026",
    "Code" : "コード",
    "Color" : "色",
    "Company" : "会社",
    "Connect with" : "に接続する",
    "Connect" : "接続する",
    "Copied" : "コピーされました",
    "Copy link" : "リンクをコピーする",
    "Copy" : "コピー",
    "Create a post" : "投稿する",
    "Create a post" : "投稿する",
    "Create stream" : "ストリームを作成する",
    "create_first_post" : "初めて投稿する.",
    "Create" : "作成",
    "Created" : "作成しました",
    "day" : "日",
    "days" : "日々",
    "Default: Latest first" : "デフォルト：最新から",
    "Delete forever" : "永遠に削除する",
    "Delete stream" : "ストリームを削除する",
    "Delete this post forever" : "この投稿を永久に削除する",
    "Delete this stream forever" : "このストリームを永久に削除する",
    "Delete_post" : "この投稿を削除してもよろしいですか？",
    "Delete_stream_note" : "このストリームを削除すると、個々の投稿は削除されません. 投稿を削除するには、個々のリンクをアクセスしてください",
    "Delete_stream" : "このストリームを削除してもよろしいですか？これは元に戻すことはできません.",
    "Delete" : "削除",
    "Deleted" : "削除されました",
    "Description" : "説明",
    "Develop" : "開発する",
    "Developer Console" : "デベロッパーコンソール",
    "Diff" : "差",
    "Disconnect" : "切断する",
    "Discussion" : "ディスカッション",
    "Done" : "完了",
    "Down votes" : "下票",
    "Downs" : "ダウンズ",
    "Drag_drop" : "ここにドラッグアンドドロップする",
    "Drop" : "ドロップ",
    "E-mail" : "Eメール",
    "Edit tags" : "タグを編集する",
    "Edit your post below:" : "以下の投稿をを編集する",
    "Edit_me" : "編集する\u2026",
    "Edit" : "編集する",
    "Embed on your site" : "あなたのサイトへ埋め込む",
    "Embed" : "埋め込む",
    "Enter web link to your image" : "あなたの画像へのウェブリンクを入力する",
    "Enter web page to fetch" : "読み込むウェブページを入力する",
    "Error" : "エラー",
    "Explore" : "検索する",
    "Feedback" : "フィードバック",
    "Filter author posts" : "著者の投稿をフィルタリングする",
    "Filter" : "フィルター",
    "Finish" : "仕上げる",
    "first_post" : "投稿はまだありません。初めて投稿する",
    "Follow" : "フォロー",
    "Followers" : "フォロワー",
    "Following" : "フォロー中",
    "Font" : "フォント",
    "Fonts" : "フォント",
    "Forgot password" : "パスワードを忘れた",
    "Forgot_password" : "パスワードを忘れましたか？パスワードをリセットするためのEメールが送信されます.",
    "Fork this post" : "このポストフォークする",
    "Fork" : "フォークする",
    "General" : "一般",
    "Go to post" : "投稿を見る",
    "Highest rated first" : "高評価から",
    "Highest rated" : "最高評価",
    "History": "歴史",
    "Hot first" : "ホットファースト",
    "Hot" : "ホット",
    "hour" : "時間",
    "hours" : "時間",
    "ID" : "証明書",
    "Images" : "画像",
    "in" : "に",
    "In" : "に",
    "Info" : "情報",
    "Install" : "インストール",
    "Joined" : "参加しました",
    "Karma" : "カーマ",
    "Language" : "言語",
    "Latest first" : "最新のものから",
    "Latest" : "最新",
    "Learn about bots" : "ボットについて学ぶ",
    "Learn more about anonymous posts" : "匿名投稿について学ぶ",
    "Learn more" : "もっと学ぶ",
    "Leave your comment" : "コメントを残す",
    "Less" : "もっと少なく",
    "Link to image" : "画像へのリンク",
    "Link to video" : "ビデオへのリンク",
    "Link to YouTube video" : "YouTube動画へのリンク",
    "Link" : "リンク",
    "Load more" : "もっと積み込む",
"Login" : "ログイン",
"Logout" : "ログアウト",
"Manage bots" : "ボットを管理する",
"Manifest" : "はっきりした",
"Mark_nudity" : "この内容はポルノ、ヌードなどの成熟したコンテンツが含まれているとマークする.",
"Markdown Help" : "マークダウンヘルプ",
"Markdown" : "マークダウン",
"minute" : "分",
"minutes" : "分",
"Moderators" : "モデレーター",
"Modified" : "変更されました",
"month" : "月",
"months" : "月",
"More pictures" : "その他の写真",
"More streams" : "その他のストリーム",
"more" : "もっと",
"More" : "もっと",
"My P's" : "私の投稿",
"My Posts" : "私の投稿",
"My streams" : "私のストリーム",
"My Streams" : "私のストリーム",
"Name" : "名前",
"New board" : "新しい板",
"New bot" : "新しいボット",
"New Post" : "新しい投稿",
"New post" : "新しい投稿",
"No_bots" : "ボットはまだ接続されていません.",
"no_posts_yet" : "投稿はまだありません",
"Oldest first" : "最古のものから",
"Oldest" : "最古",
"Optional" : "オプショナル",
"or drag image here" : "またはここに画像をドラッグする",
"P4 Components" : "P4コンポーネント",
"P4 Product" : "P4製品 ",
"Package" : "パッケージ",
"Password" : "パスワード",
"Paste image or link" : "画像またはリンクの貼り付け",
"Paste image with" : "画像を貼り付ける",
"Paste" : "貼り付け",
"Permissions" : "許可" ,
"Pick a file" : "ファイルを選択する\u2026",
"Pick file from your hard drive" : "ハードドライブからファイルを選択する",
"Picked streams" : "選択されたストリーム",
"Post on Enter" : "エンターを押して投稿する",
"Post something" : "投稿する",
"Post_anonymously" : "サインアップされたくない方は匿名で投稿することができます",
"Post_count" : "投稿",
"Post_fork" : "フォークを投稿するストリームを選択してください",
"Post" : "投稿",
"Posts" : "投稿",
"Powered" : "による支援",
"Preview" : "プレビュー",
"Privacy Policy" : "プライバシーポリシー" ,
"Privacy" : "プライバシー",
"Private" : "プライベート",
"Profile" : "プロフィール",
"Publish" : "投稿する",
"Rating" : "評価",
"Re-enter" : "再入力",
    "Read-only" : "読み取り専用",
    "Report abuse" : "不正行為を報告する",
    "Report Bugs" : "バグを報告する",
    "Report this post" : "この投稿を報告する",
    "Report_post" : "報告された投稿は毎日レビューされ、利用規約に違反しているかどうか判断されます。利用規約に違反するアカウントは終了される可能性があります",
    "Report" : "報告",
    "Reset password" : "パスワードをリセットする",
    "reset_code" : "リセットコードがEメールに送信されました。新しいパスワードと共に入力してください.",
    "Saved" : "保存されました",
    "Search" : "検索",
    "seconds" : "秒",
    "Security" : "セキュリティー",
    "See more streams" : "他のストリームを見る",
    "Select default font style for your posts" : "デフォルトフォントスタイルを選択する",
    "Select Image" : "画像を選択する",
    "Select image" : "画像を選択する",
    "Select streams where to post your fork" : "フォークを送信するストリームを選択する",
    "Send e-mail" : "Eメールを送信する",
    "Send" : "送信する",
    "Settings" : "設定",
    "Share on" : "に共有する",
    "Share" : "共有する",
    "Short Link" : "ショートリンク",
    "Short link" : "ショートリンク",
    "Shorten Link" : "リンクを短縮する",
    "Sign up" : "サインアップ",
    "Sign_with_pseudonym" : "好みに応じて、仮名またはアバターでサインしてください",
    "Slug" : "スラグ",
    "Social" : "社会",
    "Sorting" : "ソーティング",
    "Source" : "ソース",
    "Start posting right now" : "投稿を開始する",
    "Stream name" : "ストリーム名",
    "Stream" : "ストリーム",
    "Streams" : "ストリーム",
    "Style" : "スタイル",
    "Styles" : "スタイル",
    "Submit" : "提出する",
    "Tags" : "タグ",
    "Terms of Use" : "利用規約",
    "terms" : "条項",
    "This is your post" : "これはあなたの投稿です",
    "This stream is private, only you and moderators can see it" : "このストリームはプライベートです。あなた自身とモデレーターのみ拝見することができます",
    "This stream is public, anyone can see it" : "このストリームは公開されており、誰でも見ることができます",
    "Thumbnail" : "サムネイル",
    "Tip" : "ヒント",
    "Title" : "タイトル",
    "Trending first" : "今流行っているものから";
    "Trending Posts" : "流行り投稿",
    "Trending" : "今流行っている",
    "try_again" : "おっと！エラーです。しばらくしてからもう一度お試しください."
    "Type_reply" : "返信する",
    "Unfollow" : "フォローをやめる",
    "Unknown" : "不明",
    "Unnamed" : "無名",
    "Up votes" : "アップ票",
    "Upload" : "アップロード",
    "Ups" : "アップ",
    "User" : "ユーザー",
    "Username" : "ユーザー名",
    "Videos" : "動画",
    "View source" : "ソースを表示する",
    "View" : "表示",
    "Views" : "拝見回数",
    "Visit" : "訪問",
    "Want to disconnect?" : "切断したいですか？",
    "Webhooks" : "ウェブフック",
    "Worst" : "最悪",
    "years" : "年",
    "Your name" : "あなたの名前",
    "Your Streams" : "あなたのストリーム",
};
