module.exports = {
    Italic: 'イタリック',
    text: 'テキスト',
    Bold: '太字',
    Link: 'リンク',
    Highlighted: 'ハイライト',
    Strikethrough: '打ち間違い',
    Underlined: '下線',
    Super: 'スーパー',
    Emoji: '絵文字',
    Inline: 'インライン',
    tag: 'タグ',
    Heading: '見出し',
    Subheading: '小見出し',
    puss: '猫',
    'This is a block quote': 'これはブロック引用です',
    Item: 'アイテム',
    code: 'コード',
    Bill: 'ゆかりさん',
    Bob: '正太郎さん',
    'Hello there': 'こんにちは',
    Thinking: '考え中',
    Hello: 'こんにちは',
    BACK: 'リターン',
    Blocks: 'ブロック',
    Text: 'テキスト',
};
