module.exports = {
    "About us" : "Riguardo a noi",
    "About" : "Riguardo",
    "Activity" : "Attività",
    "Add bot" : "Aggiungi bot",
    "Add comment" : "Aggiungi commento",
    "Add link" : "Aggiungi link",
    "Add picture" : "Aggiungi immagine",
    "Add tags" : "Aggiungi tags",
    "Add text" : "Aggiungi testo",
    "Add Video" : "Aggiungi video",
    "Add_link_bot" : "Link al file JavaScript o al nome del pacchetto npm",
    "Add" : "Aggiungi",
    "Added" : "Aggiunto",
    "ago" : "ago",
    "and" : "e",
    "Anonymous post" : " Anonimo post",
    "Anonymous Post" : "Anonimo Post",
    "Anonymous_post_long" : "Non dimenticare di copiare il link al tuo post anonimo. Questo post non può essere eliminato finché tu o almeno un'altra persona mantenga questo collegamento. Se nessuno ha un link a questo post, questo post sarà perso per sempre. ",
    "Anyone can post into this stream" : "Chiunque può post in questo stream",
    "Attributes" : "Attributi",
    "Best" : "Migliore",
    "Blog" : "Blog",
    "Board name" : "Nome del bordo",
    "Bots" : "Bots",
    "by" : "di",
    "Card" : "Carta",
    "Change password" : "Cambia password",
    "change_password_txt" : "Vuoi cambiare la tua password? Ti invieremo una e-mail di reset password.",
    "Choose_image" : "Scegli immagine\u2026",
    "Code" : "Codice",
    "Color" : "Colore",
    "Company" : "Compagnia",
    "Connect with" : "Connetti con",
    "Connect" : "Connetti",
    "Copied" : "Copia",
    "Copy link" : "Copia collegamento",
    "Copy" : "Copia",
    "Create a post" : "Crea un post",
    "Create stream" : "Crea stream",
    "create_first_post" : "Crea il tuo primo post.",
    "Create" : "Crea",
    "Created" : "Creato",
    "day" : "giorno",
    "days" : "giorni",
    "Default: Latest first" : "Predefinito: Ultima prima",
    "Delete forever" : "Elimina per sempre",
    "Delete stream" : "Elimina stream",
    "Delete this post forever" : "Elimina questo post per sempre",
    "Delete this stream forever" : "Elimina questo stream per sempre",
    "Delete_post" : "Sei sicuro di voler eliminare questo post?",
    "Delete_stream_note" : "Tieni presente che eliminando questo stream i tuoi messaggi personali non verranno rimossi. Puoi cancellare i tuoi postes accedendo ai loro collegamenti.",
    "Delete_stream" : "Sei sicuro di voler eliminare questo stream? Non può essere annullato.",
    "Delete" : "Elimina",
    "Deleted" : "Eliminato",
    "Description" : "Descrizione",
    "Develop" : "Sviluppare",
    "Developer Console" : "Console per sviluppatori",
    "Diff" : "Diff",
    "Disconnect" : "Scollegare",
    "Discussion" : "Discussione",
    "Done" : "Fatto",
    "Down votes" : "Pollice giù",
    "Downs" : "Giù",
    "Drag_drop" : "Trascinare e rilasciare l'immagine qui",
    "Drop" : "Rilasciare",
    "E-mail" : "E-mail",
    "Edit your post below:" : "Modifica il tuo post qui sotto:",
    "Edit_me" : "Modifica me\u2026",
    "Edit" : "Modifica",
    "Embed on your site" : "Incorpora sul tuo sito",
    "Embed" : "Incorpora",
    "Enter web link to your image" : "Inserisci link web alla tua immagine",
    "Enter web page to fetch" : "Inserisci pagina web per recuperare",
    "Error" : "Errore",
    "Explore" : "Esplorare",
    "Filter author posts" : "Autore dei filtri",
    "Filter" : "Filtro",
    "Finish" : "Fine",
    "first_post" : "Nessun post ancora Crea il tuo primo post.",
    "Follow" : "Segui",
    "Followers" : "Seguaci",
    "Following" : "Seguente",
    "Font" : "Font",
    "Fonts" : "Font",
    "Forgot password" : "Password dimenticata",
    "Forgot_password" : "Hai dimenticato la password? Ti invieremo una e-mail per ripristinare la tua password",
    "Fork this post" : "Forcella questo post",
    "Fork" : "Forcella",
    "General" : "Generale",
    "Go to post" : "Vai a postare",
    "Highest rated first" : "Il più alto prima",
    "Highest rated" : "Miglior voto",
    "History": "Storia",
    "Hot first" : "Prima caldo",
    "Hot" : "Caldo",
    "hour" : "ore",
    "hours" : "ora",
    "ID" : "ID",
    "Images" : "Immagini",
    "in" : "in",
    "In" : "In",
    "Info" : "Info",
    "Install" : "Installa",
    "Joined" : "Iscritto",
    "Karma" : "Karma",
    "Language" : "Lingua",
    "Latest first" : "Ultimo primo",
    "Latest" : "Ultimo",
    "Learn about bots" : "Ulteriori informazioni sui bot",
    "Learn more about anonymous posts" : "Ulteriori informazioni sui post anonimi",
    "Learn more" : "Ulteriori informazioni",
    "Less" : "Meno",
    "Link to image" : "Link all'immagine",
    "Link to video" : "Link al video",
    "Link to YouTube video" : "Link al YouTube video",
    "Link" : "Link",
    "Load more" : "Carica di più",
    "Login" : "Accesso",
    "Logout" : "Disconnettersi",
    "Manage bots" : "Gestisci  bots",
    "Manifest" : "Manifest",
    "Mark_nudity" : "Contrassegna questo contenuto come contenuto di nudità, pornografia o altro contenuto maturo o esplicito.",
    "Markdown Help" : "Guida alla Markdown",
    "Markdown" : "Markdown",
    "minute" : "minuti",
    "minutes" : "minuti",
    "Moderators" : "Moderatori",
    "Modified" : "Modificato",
    "month" : "mese",
    "months" : "mesi",
    "More pictures" : "Altre immagini",
    "More streams" : "Altri streams",
    "more" : "altro ancora",
    "More" : "Più",
    "My P's" : "I miei Post",
    "My Posts" : "I miei post",
    "My streams" : "I miei stream",
    "My Streams" : "I miei Streams",
    "Name" : "Nome",
    "New board" : "Nuova tavola",
    "New bot" : "Nuovo bot",
    "New Post" : "Nuova Post",
    "New post" : "Nuovo post",
    "No_bots" : "Non hai ancora nessun bote collegato.",
    "no_posts_yet" : "Nessun post qui, ancora.",
    "Oldest first" : "Prima più antica",
    "Oldest" : "Più vecchio",
    "Only you and moderators can post into this stream" : "Solo tu e i moderatori puoi pubblicare in questo stream",
    "Optional" : "Opzionale",
    "or drag image here" : "oppure trascina l'immagine qui",
    "P4 Components" : "P4 Componenti",
    "P4 Product" : "P4 Prodotto",
    "Package" : "Pacchetto",
    "Password" : "Password",
    "Paste image with" : "Incolla l'immagine con",
    "Paste" : "Incolla",
    "Permissions" : "Autorizzazioni" ,
    "Pick a file" : "Scegli un file\u2026",
    "Pick file from your hard drive" : "Scegli il file dal disco rigido",
    "Picked streams" : "Streams selezionati",
    "Post_fork" : "Seleziona i streams dove inviare la tua forchetta",
    "Post_anonymously" : "NON VUOI SIGNIFICATO? POST ANONYMA",
    "Post_count" : "Postos",
    "Post something" : "Inserisci qualcosa",
    "Post" : "Post",
    "Posts" : "Postos",
    "Powered" : "Supportati da",
    "Preview" : "Anteprima",
    "Privacy Policy" : "Politica sulla privacy" ,
    "Privacy" : "Privata",
    "Private" : "Privato",
    "Profile" : "Profilo",
    "Publish" : "Pubblica",
    "Rating" : "Valutazione",
    "Re-enter" : "Reinserire",
    "Read-only" : "Sola lettura",
    "Report abuse" : "Riportare abuso",
    "Report Bugs" : "Segnala errori",
    "Report this post" : "Segnala questo post",
    "Report_post" : "I post segnalati vengono riesaminati ogni giorno per determinare se violano i nostri Termini di utilizzo. I conti che violano i nostri Termini di utilizzo possono essere interrotti.",
    "Report" : "Riportare",
    "Reset password" : "Resetta la password",
    "reset_code" : "Il codice di ripristino è stato inviato alla tua e-mail, digitalo qui con la tua nuova password",
    "Saved" : "Salvato",
    "Search" : "Ricerca",
    "seconds" : "secondi",
    "Security" : "Sicurezza",
    "See more streams" : "Guarda altri streamas",
    "Select default font style for your posts" : "Seleziona lo stile predefinito per i tuoi post",
    "Select Image" : "Seleziona immagine",
    "Send e-mail" : "Invia e-mail",
    "Send" : "Invia",
    "Settings" : "Impostazioni",
    "Share" : "Condividi",
    "Share on" : "Condividi su",
    "Short Link" : "Collegamento Link",
    "Short link" : "Collegamento link",
    "Shorten Link" : "Abbassa Link",
    "Sign up" : "Iscriviti",
    "Sign_with_pseudonym" : "Opzionale, firmare il post con pseudonimo o avatar",
    "Slug" : "Legame",
    "Social" : "Sociale",
    "Sorting" : "Ordinamento",
    "Source" : "Origine",
    "Start posting right now" : "Inizia la pubblicazione in questo momento",
    "Stream name" : "Nome stream",
    "Stream" : "Stream",
    "Streams" : "Streams",
    "Styles" : "Stili",
    "Submit" : "Invia",
    "Tags" : "Tags",
    "Terms of Use" : "Termini di utilizzo",
    "terms" : "termini",
    "This is your post" : "Questo è il tuo post",
    "This stream is private, only you and moderators can see it" : "Questo stream è privato, solo voi e i moderatori possono vederl",
    "This stream is public, anyone can see it" : "Questo stream è pubblico, chiunque può vederlo",
    "Thumbnail" : "Miniatura",
    "Tip" : "Suggerimento",
    "Title" : "Titolo",
    "Trending first" : "Trend in primo luogo",
    "Trending Posts" : "Postes di trendings",
    "Trending" : "Trend",
    "try_again" : "Oops, errore, riprova più tardi.",
    "Type_reply" : "Tipo risposta",
    "Unknown" : "Sconosciuto",
    "Unfollow" : "Annulla",
    "Unnamed" : "Senza nome",
    "Up votes" : "Pollice su",
    "Upload" : "Carica",
    "Ups" : "Su",
    "User" : "Utente",
    "Username" : "Nome utente",
    "Videos" : "Video",
    "View source" : "Visualizza sorgente",
    "View" : "Vista",
    "Views" : "Viste",
    "Visit" : "Visita",
    "Want to disconnect?" : "Vuoi scollegare?",
    "Webhooks" : "Webhooks",
    "Worst" : "Peggiore",
    "years" : "anni",
    "Your name" : "Il tuo nome",
    "Your Streams" : "I tuoi streams",
};
