module.exports = {
    Italic: 'Italico',
    text: 'testo',
    Bold: 'Grassetto',
    Link: 'Link',
    Highlighted: 'Evidenziato',
    Strikethrough: 'Barrato',
    Underlined: 'Sottolineato',
    Super: 'Super',
    Emoji: 'Emoji',
    Inline: 'In linea',
    tag: 'hashtag',
    Heading: 'Titolo',
    Subheading: 'Subtitolo',
    puss: 'gatto',
    'This is a block quote': 'Questo è un blocco quote',
    Item: 'Elenco',
    code: 'codice',
    Bill: 'Umberto',
    Bob: 'Lorenzo',
    'Hello there': 'Ciao ci',
    Thinking: 'Pensiero',
    Hello: 'Ciao',
    BACK: 'INDIETRO',
    Blocks: 'Blocchi',
    Text: 'Testo',
};
