module.exports = {
    'About us': 'Sobre',
    About: 'Sobre Nosotros',
    Activity: 'Actividad',
    'Add bot': 'Añadir bot',
    'Add comment': 'Añadir comentario',
    'Add link': 'Añadir enlace',
    'Add picture': 'Añadir imagen',
    'Add tags': 'Añadir etiquetas',
    'Add text': 'Añadir texto',
    'Add Video': 'Añadir vídeo',
    Add_link_bot: 'Enlace al fila JavaScript o nombre del paquete npm',
    Add: 'Añadir',
    Added: 'Añadido',
    ago: 'hace',
    and: 'y',
    'Anonymous post': 'Puesto anónimo',
    'Anonymous Post': 'Puesto Anónimo',
    Anonymous_post_long:
        'No olvide copiar el enlace a su post anónima. Esta post no se puede eliminar siempre y cuando usted o al menos otra persona mantenga este enlace. Si nadie tiene un enlace a este post, este mensaje se perderá para siempre. ',
    'Anyone can post into this stream': 'Cualquiera puede publicar en este stream',
    Attributes: 'Attributos',
    Best: 'Mejor',
    Blog: 'Blog',
    'Board name': 'Nombre de el Bordo',
    Bots: 'Bots',
    by: 'por',
    Card: 'Tarjeta',
    'Change password': 'Cambia la contraseña',
    change_password_txt:
        '¿Quieres cambiar tu contraseña? Te enviaremos un correo electrónico de restablecimiento de contraseña.',
    Choose_image: 'Elegir imagen\u2026',
    Code: 'Código',
    Color: 'Color',
    Company: 'Compañía',
    'Connect with': 'Conectar con',
    Connect: 'Conectar',
    Copied: 'Copiado',
    'Copy link': 'Copiar enlace',
    Copy: 'Copiar',
    'Create a post': 'Crear un puesto',
    'Create stream': 'Crear stream',
    create_first_post: 'Crear primera puesto',
    Create: 'Crear',
    Created: 'Creado',
    day: 'día',
    days: 'días',
    'Default: Latest first': 'Predeterminado: Últimos primeros',
    'Delete forever': 'Eliminar para siempre',
    'Delete stream': 'Eliminar stream',
    'Delete this post forever': 'Eliminar un puesto para siempre',
    'Delete this stream forever': 'Eliminar este stream para siempre',
    Delete_post: '¿Estás seguro de que quieres eliminar est puesto?',
    Delete_stream_note:
        'Tenga en cuenta que al eliminar este stream sus postes individuales no se eliminarán. Puedes eliminar tus postes accediendo a sus enlaces.',
    Delete_stream: '¿Seguro que quieres eliminar esta stream? Esto no se puede deshacer.',
    Delete: 'Borrar',
    Deleted: 'Eliminado',
    Description: 'Descripción',
    Develop: 'Desarrollar',
    'Developer Console': 'Consola de desarrollador',
    Diff: 'Dif',
    Disconnect: 'Desconectar',
    Discussion: 'Discusión',
    Done: 'Hecho',
    'Down votes': 'Pulgares abajo',
    Downs: 'Abajo',
    Drag_drop: 'Arrastrar y soltar la imagen aquí',
    Drop: 'Soltar',
    'E-mail': 'E-mail',
    Edit_me: 'Edítame\u2026',
    'Edit your post below:': 'Edite su puesto a continuación:',
    Edit: 'Editar',
    'Embed on your site': 'Empotrar en tu sitio',
    Embed: 'Empotrar',
    'Enter web link to your image': 'Ingresa el enlace web a tu imagen',
    'Enter web page to fetch': 'Ingresar a la página web para buscar',
    Error: 'Error',
    Explore: 'Explorar',
    'Filter author posts': 'Filtrar puestos de autor',
    Filter: 'Filtrar',
    Finish: 'Terminar',
    first_post: 'Aún no puestos entradas, crea tu primera puesto.',
    Follow: 'Seguir',
    Followers: 'Seguidores',
    Following: 'Siguiendo',
    Font: 'Fuente',
    Fonts: 'Fuentes',
    'Forgot password': 'Olvidaste tu contraseña',
    Forgot_password: '¿Olvidaste tu contraseña? Le enviaremos un correo electrónico para restablecer su contraseña.',
    'Fork this post': 'Bifurcar un puesto',
    Fork: 'Bifurcar',
    General: 'General',
    'Go to post': 'Ir a la puesto',
    'Highest rated first': 'Mayor puntuación primero',
    'Highest rated': 'El mejor valorado',
    History: 'Historia',
    'Hot first': 'Primero caliente',
    Hot: 'Caliente',
    hour: 'hora',
    hours: 'horas',
    ID: 'ID',
    Images: 'Imágenes',
    in: 'en',
    In: 'En',
    Info: 'Info',
    Install: 'Instalar',
    Joined: 'Unido',
    Karma: 'Karma',
    Language: 'Lenguaje',
    'Latest first': 'Últimos primeros',
    Latest: 'Último',
    'Learn about bots': 'Conozca los bots',
    'Learn more about anonymous posts': 'Más información sobre puestos anónimas',
    'Learn more': 'Más información',
    Less: 'Menos',
    'Link to image': 'Enlace a la imagen',
    'Link to video': 'Link al video',
    'Link to YouTube video': 'Link al YouTube video',
    Link: 'Enlazar',
    'Load more': 'Cargar más',
    Login: 'Iniciar sesión',
    Logout: 'Cerrar sesión',
    'Manage bots': 'Administrar bots',
    Manifest: 'Manifest',
    Mark_nudity: 'Marcar este contenido como conteniendo desnudos, pornografía u otro contenido maduro o explícito.',
    'Markdown Help': 'Ayuda de Markdown',
    Markdown: 'Markdown',
    minute: 'minuto',
    minutes: 'minutos',
    Moderators: 'Moderatores',
    Modified: 'Modificado',
    month: 'mes',
    months: 'meses',
    'More pictures': 'Más imagen',
    'More streams': 'Más streams',
    more: 'más',
    More: 'Más',
    "My P's": 'Mis Puestos',
    'My Posts': 'Mis Puestos',
    'My streams': 'Mis streamas',
    'My Streams': 'Mis Streamas',
    Name: 'Nombre',
    'New board': 'Nuevo bordo',
    'New bot': 'Nuevo bot',
    'New Post': 'Neuvo Puesto',
    'New post': 'Nueva post',
    No_bots: 'Todavía no tienes ningún bots conectado.',
    no_posts_yet: 'No puestos aquí, todavía',
    'Oldest first': 'Los más antiguos primero',
    Oldest: 'Más antiguo',
    'Only you and moderators can post into this stream': 'Sólo tú y los moderadores podéis publicar en este stream',
    Optional: 'Opcional',
    'or drag image here': 'o arrastra la imagen aquí',
    'P4 Components': 'P4 Componentes',
    'P4 Product': 'P4 Producto',
    Package: 'Paquete',
    Password: 'Contraseña',
    'Paste image with': 'Pegar imagen con',
    Paste: 'Pegar',
    Permissions: 'Permisos',
    'Pick a file': 'Elige un fila\u2026',
    'Pick file from your hard drive': 'Elija el archivo de su disco duro',
    'Picked streams': 'Rutas streams',
    Post_anonymously: 'NO QUIERE FIRMAR? POST ANÓNIMO',
    Post_fork: 'Stream los arroyos donde post tu bifurcar',
    Post_count: 'Puestos',
    'Post something': 'Publicar algo',
    Post: 'Enviar',
    Posts: 'Puestos',
    Powered: 'Con el apoyo de',
    Preview: 'Preestreno',
    'Privacy Policy': 'Política de privacidad',
    Privacy: 'Privacidad',
    Private: 'Privacidad',
    Profile: 'Perfil',
    Publish: 'Publicar',
    Rating: 'Valuación',
    'Re-enter': 'Volver a entrar en',
    'Read-only': 'Sólo lectura',
    'Report abuse': 'Reportar abuso',
    'Report Bugs': 'Reportar errores',
    'Report this post': 'Reportar este puesto',
    Report_post:
        'Los puestos reportados son revisados diariamente para determinar si violan nuestros Términos de Uso. Las cuentas que violen nuestros Términos de Uso pueden ser terminadas.',
    Report: 'Denunciar',
    'Reset password': 'Restablecer la contraseña',
    reset_code: 'Se ha enviado el código de restablecimiento a su e-mail, escríbalo aquí con su nueva contraseña.',
    Saved: 'Guardado',
    Search: 'Buscar',
    seconds: 'segundos',
    Security: 'Seguridad',
    'See more streams': 'Ver más streams',
    'Select default font style for your posts': 'Selecciona el estilo de fuente predeterminado para tus puestos',
    'Select Image': 'Seleccionar imagen',
    'Send e-mail': 'Enviar e-mail',
    Send: 'Enviar',
    Settings: 'Ajustes',
    'Share on': 'Compartir en',
    Share: 'Compartir',
    'Short Link': 'Enlace Corto',
    'Short link': 'Enlace сorto',
    'Shorten Link': 'Acortar el enlace',
    'Sign up': 'Regístrate',
    Sign_with_pseudonym: 'Opcionalmente, puede firmar el puesto con pseudónimo o avatar',
    Slug: 'Enlace',
    Social: 'Social',
    Sorting: 'Clasificación',
    Source: 'Fuente',
    'Start posting right now': 'Comenzar a publicar ahora',
    'Stream name': 'Nombre de la stream',
    Stream: 'Stream',
    Streams: 'Streamas',
    Styles: 'Estilos',
    Submit: 'Enviar',
    Tags: 'Etiquetas',
    'Terms of Use': 'Términos de Uso',
    terms: 'condiciones',
    'This is your post': 'Esta es tu puesto',
    'This stream is private, only you and moderators can see it':
        'Este stream es privado, sólo tú y los moderadores puedes verlo',
    'This stream is public, anyone can see it': 'Este stream es público, cualquiera puede verlo',
    Thumbnail: 'Miniatura',
    Tip: 'Sugerencia',
    Title: 'Título',
    'Trending first': 'Tendencia primero',
    'Trending Posts': 'Puestos de tendencia',
    Trending: 'Tendencias',
    try_again: 'Error, vuelve a intentarlo más tarde.',
    'Type reply': 'Escriba respuesta',
    Unfollow: 'Deja de seguir',
    Unknown: 'Desconocido',
    Unnamed: 'Sin nombre',
    'Up votes': 'Pulgares hacia arriba',
    Upload: 'Subir',
    Ups: 'Arriba',
    User: 'Usuario',
    Username: 'Nombre de usuario',
    Videos: 'Videos',
    'View source': 'Ver código fuente',
    View: 'Ver',
    Views: 'Puntos de vista',
    Visit: 'Visita',
    'Want to disconnect?': '¿Quieres desconectarte?',
    Webhooks: 'Webhooks',
    Worst: 'Peor',
    years: 'años',
    'Your name': 'Tu nombre',
    'Your Streams': 'Tus streamas',
};
