module.exports = {
    Italic: 'Cursiva',
    text: 'texto',
    Bold: 'Negrita',
    Link: 'Enlace',
    Highlighted: 'Destacado',
    Strikethrough: 'Tachado',
    Underlined: 'Subrayado',
    Super: 'Súper',
    Emoji: 'Emoji',
    Inline: 'En línea',
    tag: 'hastag',
    Heading: 'Titulo',
    Subheading: 'Subtítulo',
    puss: 'gato',
    'This is a block quote': 'Esto es una cita',
    Item: 'Lista',
    code: 'código',
    Bill: 'Juan',
    Bob: 'Pedro',
    'Hello there': 'Hola hola',
    Thinking: 'Pensando',
    Hello: 'Hola',
    BACK: 'ATRAS',
    Blocks: 'Bloques',
    Text: 'Texto',
};
