module.exports = {
    'About us': 'À propos de nous',
    'About yourself\u2026': 'A propos de vous\u2026',
    About: 'À propos',
    Activity: 'Activité',
    'Add bot': 'Ajouter un bot',
    'Add comment': 'Ajouter un commentaire',
    'Add link': 'Ajouter un lien',
    'Add picture': 'Ajouter une image',
    'Add tags': 'Ajouter une étiquette',
    'Add text': 'Ajouter du texte',
    'Add Video': 'Ajouter une vidéo',
    Add_link_bot: 'Lien vers fichier JavaScript ou nom du paquet npm',
    Add: 'Ajouter',
    Added: 'Ajouté',
    ago: 'il y a',
    and: 'et',
    'Anonymous post': 'Publication anonyme',
    'Anonymous Post': 'Publication Anonyme',
    Anonymous_post_long:
        "N'oubliez pas de copier le lien vers votre publication anonyme. Cette publication ne peut pas être supprimée tant qu'au moins une personne possède le lien. Si personne n'a de lien vers votre publication, elle sera perdue pour toujours. ",
    'Anyone can post into this stream': "N'importe qui peut publier dans ce stream",
    Attributes: 'Attributs',
    Best: 'Meilleur',
    Blog: 'Blog',
    'Board name': 'Nom du tableau',
    Bots: 'Bots',
    by: 'par',
    Card: 'Carte',
    'Change password': 'Modifier le mot de passe',
    change_password_txt:
        'Vous voulez changer votre mot de passe? Nous vous enverrons un e-mail de réinitialisation du mot de passe.',
    Choose_image: "Choisir l'image\u2026",
    Code: 'Code',
    Color: 'Couleur',
    Company: 'Compagnie',
    'Connect with': 'Connectez-vous avec',
    Connect: 'Connecter',
    Copied: 'Copié',
    'Copy link': 'Copier le lien',
    Copy: 'Copier',
    'Create a post': 'Créer une publication',
    'Create stream': 'Créer un stream',
    create_first_post: 'Créez votre première publication',
    Create: 'Créer',
    Created: 'Créé',
    day: 'jour',
    days: 'jours',
    'Default: Latest first': 'Par défaut: Le plus récent en premier',
    'Delete forever': 'Supprimer pour toujours',
    'Delete stream': 'Supprimer le stream',
    'Delete this post forever': 'Supprimer cette publication pour toujours',
    'Delete this stream forever': 'Supprimer ce stream pour toujours',
    Delete_post: 'Etes-vous sûr(e) de vouloir supprimer cette publication?',
    Delete_stream_note:
        "Notez qu'en supprimant ce stream, vos publications individuelles ne seront pas supprimées. Vous pouvez supprimer vos publications en accédant à leurs liens.",
    Delete_stream: 'Êtes-vous sûr de vouloir supprimer ce stream? Ça ne peut pas être annulé.',
    Delete: 'Supprimer',
    Deleted: 'Supprimé',
    Description: 'Description',
    Develop: 'Développer',
    'Developer Console': 'Console du développeur',
    Diff: 'Diff',
    Disconnect: 'Déconnecter',
    Discussion: 'Discussion',
    Done: 'Fait',
    'Down votes': 'Pouces vers le bas',
    Downs: 'Négatifs',
    Drag_drop: "Glissez et déposez l'image ici",
    Drop: 'Déposer',
    'E-mail': 'E-mail',
    'Edit tags': 'Editer les marqueurs',
    'Edit your post below:': 'Éditez votre publication ci-dessous:',
    Edit_me: 'Éditez moi\u2026',
    Edit: 'Éditer',
    'Embed on your site': 'Intégrer dans votre site',
    Embed: 'Intégrer',
    'Enter web link to your image': 'Entrez le lien Web vers votre image',
    'Enter web page to fetch': 'Entrez la page Web à récupérer',
    Error: 'Erreur',
    Explore: 'Explorer',
    Feedback: 'Retour',
    'Filter author posts': "Filtrer les publications de l'auteur",
    Filter: 'Filtrer',
    Finish: 'Terminer',
    first_post: 'Pas encore de publications. Créez votre première publication.',
    Follow: "S'abonner",
    Followers: 'Abonnés',
    Following: 'Abonnements',
    Font: 'Police',
    Font: 'Polices',
    'Forgot password': 'Mot de passe oublié',
    Forgot_password: 'Mot de passe oublié? Nous vous enverrons un e-mail pour réinitialiser votre mot de passe.',
    'Fork this post': 'Bifurquer cette publication',
    Fork: 'Bifurquer',
    General: 'Général',
    'Go to post': 'Accéder le post',
    'Highest rated first': 'Les mieux notés en premier',
    'Highest rated': 'Plus hauts classés',
    History: "L'Histoire",
    'Hot first': 'Classé meilleur',
    Hot: 'Chaud',
    hour: 'heure',
    hours: 'heures',
    ID: 'ID',
    Images: 'Images',
    in: 'dans',
    In: 'Dans',
    Info: 'Info',
    Install: 'Installer',
    Joined: 'Inscrit',
    Karma: 'Karma',
    Language: 'Langue',
    'Latest first': 'Dernier premier',
    Latest: 'plus récent',
    'Learn about bots': 'En savoir plus sur les bots',
    'Learn more about anonymous posts': 'En apprendre plus sur les posts anonymes',
    'Learn more': 'En apprendre plus',
    'Leave your comment': 'Laissez votre commentaire',
    Less: 'Moins',
    'Link to image': "Lien vers l'image",
    'Link to video': 'Lien vers la vidéo',
    'Link to YouTube video': 'Lien vers la vidéo Youtube',
    Link: 'Lien',
    'Load more': 'Charger plus',
    Login: 'Se connecter',
    Logout: 'Déconnexion',
    'Manage bots': 'Gérer les bots',
    Manifest: 'Manifeste',
    Mark_nudity:
        "Marquer ce contenu comme contenant de la nudité, de la pornographie ou d'autres contenus matures ou explicites.",
    'Markdown Help': 'Aide Markdown',
    Markdown: 'Markdown',
    minute: 'minute',
    minutes: 'minutes',
    Moderators: 'Modérateurs',
    Modified: 'Modifié',
    month: 'mois',
    months: 'mois',
    'More pictures': "Plus d'images",
    'More streams': 'Plus de streams',
    more: 'plus',
    More: 'Plus',
    "My P's": 'Мes Publications',
    'My Posts': 'Mes Publications',
    'My streams': 'Mes streams',
    'My Streams': 'Mes Streams',
    Name: 'Nom',
    'New board': 'Nouveau Bord',
    'New bot': 'Nouveau robot',
    'New Post': 'Nouvelle publication',
    'New post': 'Nouvelle publication',
    No_bots: "Vous n'avez pas encore de bots connectés.",
    no_posts_yet: 'Pas encore de publications ici',
    'Oldest first': "Plus ancien d'abord",
    Oldest: 'Plus ancien',
    'Only you and moderators can post into this stream': 'Seuls vous et les modérateurs peuvent publier dans ce stream',
    Optional: 'Optionnel',
    'or drag image here': "ou faites glisser l'image ici",
    'P4 Components': 'Composants P4',
    'P4 Product': 'Produit P4',
    Package: 'Forfait',
    Password: 'Mot de passe',
    'Paste image or link': "Coller l'image ou le lien",
    'Paste image with': "Coller l'image avec",
    Paste: 'Coller',
    Permissions: 'Permissions',
    'Pick a file': 'Choisir un fichier\u2026',
    'Pick file from your hard drive': 'Choisissez le fichier à partir de votre disque dur',
    'Picked streams': 'Streams sélectionnés',
    'Post on Enter': 'Publier en cliquant sur Entrer',
    'Post something': 'Publier quelque chose',
    Post_anonymously: 'VOUS NE VOULEZ PAS VOUS INSCRIRE? PUBLIEZ ANONYMEMENT',
    Post_count: 'Publications',
    Post_fork: 'Sélectionnez le stream',
    Post: 'Publication',
    Posts: 'Publications',
    Powered: 'Supporté par',
    Preview: 'Aperçu',
    'Privacy Policy': 'Politique de confidentialité',
    Privacy: 'Confidentialité',
    Private: 'Privé',
    Profile: 'Profil',
    Publish: 'Publier',
    Rating: 'Classement',
    'Re-enter': 'Ré-insérer',
    'Read-only': 'Lecture seule',
    'Report abuse': 'Signaler un abus',
    'Report Bugs': 'Signaler un bogue',
    'Report this post': 'Signaler cette publication',
    Report_post:
        "Les publications déclarées sont passées en revue tous les jours pour déterminer leur compatibilité à nos conditions d'utilisation. Les comptes qui violent nos conditions d'utilisation peuvent être supprimés.",
    Report: 'Signaler',
    'Reset password': 'Réinitialiser le mot de passe',
    reset_code:
        'Le code de réinitialisation vous a été envoyé par e-mail, insérez le ici avec votre nouveau mot de passe.',
    Saved: 'Sauvegardé',
    Search: 'Rechercher',
    seconds: 'secondes',
    Security: 'Sécurité',
    'See more streams': 'Voir plus de streams',
    'Select default font style for your posts': 'Sélectionner la police par défaut de vos publications',
    'Select Image': "Sélectionner l'image",
    'Select image': 'Sélectionner une image',
    'Select streams where to post your fork': 'Sélectionnez le stream où poster',
    'Send e-mail': 'Envoyer un e-mail',
    Send: 'Envoyer',
    Settings: 'Paramètres',
    'Share on': 'Partager sur',
    Share: 'Partager',
    'Short Link': 'Lien Court',
    'Short link': 'Lien Court',
    'Shorten Link': 'Raccourcir le lien',
    'Sign up': "S'inscrire",
    Sign_with_pseudonym: 'Optionellement, signez le message avec un pseudonyme ou un avatar',
    Slug: 'Lien',
    Social: 'Social',
    Sorting: 'Triage',
    Source: 'Source',
    'Start posting right now': 'Commencez à publier dès maintenant',
    'Stream name': 'Nom du stream',
    Stream: 'Stream',
    Streams: 'Streams',
    Style: 'Style',
    Styles: 'Style',
    Submit: 'Soumettre',
    Tags: 'Marqueurs',
    'Terms of Use': "Conditions d'utilisation",
    terms: 'conditions',
    'This is your post': 'Ceci est votre publication',
    'This stream is private, only you and moderators can see it':
        'Ce stream est privé, seul vous et les modérateurs peuvent le voir',
    'This stream is public, anyone can see it': 'Ce stream est public, tout le monde peut le voir',
    Thumbnail: 'Imagette',
    Tip: 'Conseil',
    Title: 'Titre',
    'Trending first': 'Populaire',
    'Trending Posts': 'Publications populaires',
    Trending: 'Tendance',
    try_again: 'Oups! Erreur, réessayez plus tard.',
    Type_reply: 'Insérer la réponse',
    Unfollow: 'Se désabonner',
    Unknown: 'Inconnu',
    Unnamed: 'Sans nom',
    'Up votes': 'Pouces vers le haut',
    Upload: 'Télécharger',
    Ups: 'Positifs',
    User: 'Utilisateur',
    Username: "Nom d'utilisateur",
    Videos: 'Vidéos',
    'View source': 'Afficher la source',
    View: 'Afficher',
    Views: 'Vues',
    Visit: 'Visiter',
    'Want to disconnect?': 'Voulez-vous vous déconnecter?',
    Webhooks: 'Webhooks',
    Worst: 'Pire',
    years: 'années',
    'Your name': 'Votre nom',
    'Your Streams': 'Vos Streams',
};
