module.exports = {
    'About us': 'À propos de nous',
    About: 'À peu près',
    Activity: 'Activité',
    'Add bot': 'Ajouter bot',
    'Add comment': 'Ajouter un commentaire',
    'Add link': 'Ajouter lien',
    'Add picture': 'Ajouter une image',
    'Add tags': 'Ajouter une marque',
    'Add text': 'Ajouter du texte',
    'Add Video': 'Ajouter une vidéo',
    Add_link_bot: 'Lien vers le fichier JavaScript ou le nom du paquet npm',
    Add: 'Ajouter',
    Added: 'Ajouté',
    ago: 'il',
    and: 'et',
    'Anonymous post': 'Poste anonyme',
    'Anonymous Post': 'Poste Anonyme',
    Anonymous_post_long:
        "N'oubliez pas de copier le lien vers votre poste anonyme. Cette post ne peut pas être supprimée tant que vous ou au moins une autre personne conservez ce lien. Si personne n'a de lien vers cette publication, cette publication sera perdue pour toujours. ",
    'Anyone can post into this stream': "N'importe qui peut publier dans ce stream",
    Attributes: 'Attributs',
    Best: 'Meilleur',
    Blog: 'Blog',
    'Board name': 'Nom de la Bord',
    Bots: 'Bots',
    by: 'par',
    Card: 'Carte',
    'Change password': 'Modifier le mot de passe',
    change_password_txt:
        'Voulez-vous changer votre mot de passe? Nous vous enverrons un e-mail de réinitialisation de mot de passe.',
    Choose_image: "Choisissez l'image\u2026",
    Code: 'Code',
    Color: 'Couleur',
    Company: 'Compagnie',
    'Connect with': 'Connectez-vous avec',
    Connect: 'Connectez',
    Copied: 'Copié',
    'Copy link': 'Copier le lien',
    Copy: 'Copier',
    'Create a post': 'Créer un poste',
    'Create stream': 'Créer un stream',
    create_first_post: 'Créer votre première poste',
    Create: 'Créer',
    Created: 'Créé',
    day: 'jour',
    days: 'jours',
    'Default: Latest first': 'Par défaut: Dernier premier',
    'Delete forever': 'Supprimer pour toujours',
    'Delete stream': 'Supprimer le stream',
    'Delete this post forever': 'Supprimez cette poste pour toujours',
    'Delete this stream forever': 'Supprimez ce stream pour toujours',
    Delete_post: 'Es-tu sur de vouloir supprimer cette poste?',
    Delete_stream_note:
        "Notez qu'en supprimant ce stream, vos posts individuels ne seront pas supprimés. Vous pouvez supprimer vos posts en accédant à leurs liens.",
    Delete_stream: 'Êtes-vous sûr de vouloir supprimer ce stream? Ça ne peut pas être annulé.',
    Delete: 'Supprimer',
    Deleted: 'Supprimé',
    Description: 'Description',
    Develop: 'Développer',
    'Developer Console': 'Console du développeur',
    Diff: 'Diff',
    Disconnect: 'Déconnexion',
    Discussion: 'Discussion',
    Done: 'Fait',
    'Down votes': 'Pouces vers le bas',
    Downs: 'Bas',
    Drag_drop: "Glisser-déposer l'image ici",
    Drop: 'Déposer',
    'E-mail': 'E-mail',
    'Edit your post below:': 'Éditez votre poste ci-dessous:',
    Edit_me: 'Éditez moi\u2026',
    Edit: 'Éditez',
    'Embed on your site': 'Intégrer sur votre site',
    Embed: 'Intégrer',
    'Enter web link to your image': 'Entrez le lien Web vers votre image',
    'Enter web page to fetch': 'Entrez la page Web à récupérer',
    Error: 'Erreur',
    Explore: 'Explorer',
    'Filter author posts': "Filtrer les postes de l'auteur",
    Filter: 'Filtre',
    Finish: 'Terminer',
    first_post: 'Pas encore de postes. Créez votre premier poste',
    Follow: 'Suis',
    Followers: 'Suivants',
    Following: 'Suivante',
    Font: 'Fonte',
    Fonts: 'Fontes',
    'Forgot password': 'Mot de passe oublié',
    Forgot_password: 'Mot de passe oublié? Nous vous enverrons un e-mail pour réinitialiser votre mot de passe.',
    'Fork this post': 'Bifurquer ce poste',
    Fork: 'Bifurquer',
    General: 'Général',
    'Go to post': 'Aller au poste',
    'Highest rated first': 'Les mieux notés en premier',
    'Highest rated': 'Meilleur classé',
    History: 'Histoire',
    'Hot first': 'Chaud premier',
    Hot: 'Chaud',
    hour: 'heure',
    hours: 'heures',
    ID: 'ID',
    Images: 'Images',
    in: 'en',
    In: 'En',
    Info: 'Info',
    Install: 'Installer',
    Joined: 'Inscrit',
    Karma: 'Karma',
    Language: 'Langue',
    'Latest first': 'Dernier premier',
    Latest: 'Dernier',
    'Learn about bots': 'En savoir plus sur les bots',
    'Learn more about anonymous posts': 'En savoir plus sur les postes anonymes',
    'Learn more': 'Apprenez-en plus',
    Less: 'Moins',
    'Link to image': "Lien vers l'image",
    'Link to video': 'Lien vers la vidéo',
    'Link to YouTube video': 'Lien vers YouTube video',
    Link: 'Lien',
    'Load more': 'Charger plus',
    Login: 'Connexion',
    Logout: 'Déconnexion',
    'Manage bots': 'Gérer les bots',
    Manifest: 'Manifeste',
    Mark_nudity:
        "Marquez ce contenu comme contenant de la nudité, de la pornographie ou d'autres contenus matures ou explicites.",
    'Markdown Help': 'Aide Markdown',
    Markdown: 'Markdown',
    minute: 'minute',
    minutes: 'minutes',
    Moderators: 'Modérateurs',
    Modified: 'Modifié',
    month: 'mois',
    months: 'mois',
    'More pictures': 'Plus de images',
    'More streams': 'Plus de streams',
    more: 'plus',
    More: 'Plus',
    "My P's": 'Мes Postes',
    'My Posts': 'Mes Postes',
    'My streams': 'Mes streams',
    'My Streams': 'Mes Streams',
    Name: 'Nom',
    'New board': 'Nouveau Bord',
    'New bot': 'Nouveau robot',
    'New Post': 'Nouveau Poste',
    'New post': 'Nouvelle post',
    No_bots: "Vous n'avez pas encore de bots connectés.",
    no_posts_yet: 'Pas encore de postes ici',
    'Oldest first': "Plus ancien d'abord",
    Oldest: 'Plus ancien',
    'Only you and moderators can post into this stream': 'Seuls vous et les modérateurs pouvez publier dans ce stream',
    Optional: 'Optionnel',
    'or drag image here': "ou faites glisser l'image ici",
    'P4 Components': 'P4 Composants',
    'P4 Product': 'P4 Produit ',
    Package: 'Forfait',
    Password: 'Mot de passe',
    'Paste image with': "Coller l'image avec",
    Paste: 'Coller',
    Permissions: 'Autorisations',
    'Pick a file': 'Choisissez un fichier\u2026',
    'Pick file from your hard drive': 'Choisissez le fichier à partir de votre disque dur',
    'Picked streams': 'Courants sélectionnés',
    'Post something': 'Publier quelque chose',
    Post_anonymously: "NE VEUT PAS S'INSCRIRE? POSTER ANONYME",
    Post_count: 'Postes',
    Post_fork: 'Select streams where to post your fork',
    Post: 'Poste',
    Posts: 'Postes',
    Powered: 'Supporté par',
    Preview: 'Aperçu',
    'Privacy Policy': 'Politique de confidentialité',
    Privacy: 'Confidentialité',
    Private: 'Privé',
    Profile: 'Profil',
    Publish: 'Publier',
    Rating: 'Évaluation',
    'Re-enter': 'Re-entrer',
    'Read-only': 'Lecture seule',
    'Report abuse': 'Rapporter un abus',
    'Report Bugs': 'Rapporter Bogues',
    'Report this post': 'Raporter cette poste',
    Report_post:
        "Les postes déclarés sont revus tous les jours pour déterminer s'ils violent nos conditions d'utilisation. Les comptes qui violent nos conditions d'utilisation peuvent être résiliés.",
    Report: 'Rapporter',
    'Reset password': 'Réinitialiser le mot de passe',
    reset_code: 'Le code de réinitialisation a été envoyé à votre e-mail, tapez ici avec votre nouveau mot de passe.',
    Saved: 'Sauvé',
    Search: 'Rechercher',
    seconds: 'secondes',
    Security: 'Sécurité',
    'See more streams': 'Voir plus de streams',
    'Select default font style for your posts': 'Sélectionnez le style de police par défaut pour vos posts',
    'Select Image': "Sélectionner l'image",
    'Send e-mail': 'Envoyer un e-mail',
    Send: 'Envoyer',
    Settings: 'Paramètres',
    'Share on': 'Partager sur',
    Share: 'Partager',
    'Short Link': 'Lien Court',
    'Short link': 'Lien Court',
    'Shorten Link': 'Raccourcir le lien',
    'Sign up': 'Inscrivez-vous',
    Sign_with_pseudonym: 'En option, signez le message avec un pseudonyme ou un avatar',
    Slug: 'Lien',
    Social: 'Social',
    Sorting: 'Tri',
    Source: 'Source',
    'Start posting right now': 'Commencez à publier dès maintenant',
    'Stream name': 'Nom du stream',
    Stream: 'Stream',
    Streams: 'Streams',
    Styles: 'Style',
    Submit: 'Soumettre',
    Tags: 'Tags',
    'Terms of Use': "Conditions d'utilisation",
    terms: 'Termes',
    'This is your post': "C'est votre post",
    'This stream is private, only you and moderators can see it':
        'Ce stream est privé, seul vous et les modérateurs peuvent le voir',
    'This stream is public, anyone can see it': 'Ce stream est public, tout le monde peut le voir',
    Thumbnail: 'Miniature',
    Tip: 'Tip',
    Title: 'Titre',
    'Trending first': 'Tendance première',
    'Trending Posts': 'Posts de tendance',
    Trending: 'Tendance',
    try_again: 'Oups! Erreur, réessayez plus tard.',
    Type_reply: 'Taper la réponse',
    Unfollow: 'Ne pas suivre',
    Unknown: 'Inconnu',
    Unnamed: 'Sans nom',
    'Up votes': 'Pouces vers le haut',
    Upload: 'Télécharger',
    Ups: 'Haut',
    User: 'Utilisateur',
    Username: "Nom d'utilisateur",
    Videos: 'Vidéos',
    'View source': 'Afficher la source',
    View: 'Afficher',
    Views: 'Vues',
    Visit: 'Visiter',
    'Want to disconnect?': 'Voulez-vous déconnecter?',
    Webhooks: 'Webhooks',
    Worst: 'Pire',
    years: 'années',
    'Your name': 'Votre nom',
    'Your Streams': 'Votre Streams',
};
