module.exports = {
    Italic: 'Italique',
    text: 'texte',
    Bold: 'Gras',
    Link: 'Lien',
    Highlighted: 'Surligner',
    Strikethrough: 'Tressé',
    Underlined: 'Souligné',
    Super: 'Super',
    Emoji: 'Emoji',
    Inline: 'En ligne',
    tag: 'hashtag',
    Heading: 'Titre',
    Subheading: 'Soustitre',
    puss: 'chat',
    'This is a block quote': 'Ceci est une citation',
    Item: 'Lista',
    code: 'code',
    Bill: 'Louis',
    Bob: 'Hugo',
    'Hello there': 'Bonjour',
    Thinking: 'Pensant',
    Hello: 'Bonjour',
    BACK: 'RETOUR',
    Blocks: 'Blocs',
    Text: 'Texte',
};
