module.exports = {
    'About us': 'О нас',
    About: 'О вас',
    Activity: 'Активность',
    'Add bot': 'Добавить бота',
    'Add comment': 'Добавить коментарий',
    'Add link': 'Добавить ссылку',
    'Add picture': 'Добавить картинку',
    'Add tags': 'Добавить теги',
    'Add text': 'Добавить текст к картинке',
    'Add Video': 'Добавить видео',
    Add_link_bot: 'Ссылка на JavaScript файл или имя пакета npm',
    Add: 'Добавить',
    Added: 'Добавлено',
    ago: 'назад',
    and: 'и',
    'Anonymous Post': 'Анонимный Пост',
    'Anonymous post': 'Анонимный пост',
    Anonymous_post_long:
        'Не забудьте скопировать ссылку на анонимный пост. Этот пост не может быть удален, пока вы или как мининмум еще один человек имеет эту ссылку. Если ни у кого не будет ссылки на этот пост, этот пост будет потерян навсегда.',
    'Anyone can post into this stream': 'Все могут писать в этот стрим',
    Attributes: 'Атрибуты',
    Best: 'Лучшее',
    Blog: 'Блог',
    'Board name': 'Название коллекции',
    Bots: 'Боты',
    by: 'от',
    Card: 'Карточка',
    'Change password': 'Поменять пароль',
    change_password_txt: 'Хотите поменять пароль? Мы отправим вам е-майл для смены пароля.',
    Choose_image: 'Выбрать картинку',
    Code: 'Код',
    Color: 'Цвет',
    Company: 'Компания',
    'Connect with': 'Подсоединиться к',
    Connect: 'Подсоединиться',
    Copied: 'Скопировано',
    'Copy link': 'Копировать ссылку',
    Copy: 'Копировать',
    'Create a post': 'Создать пост',
    'Create stream': 'Создать стрим',
    create_first_post: 'Создать первый пост',
    Create: 'Создать',
    Created: 'Создан',
    day: 'день',
    days: 'дней',
    'Default: Latest first': 'По умолчанию: последний первый',
    'Delete forever': 'Удалить навсегда',
    'Delete stream': 'Удалить стрим',
    'Delete this post forever': 'Навсегда удалить этот пост',
    'Delete this stream forever': 'Навсегда удалить этот стрим',
    Delete_post: 'Вы уверены, что хотите удалить этот пост?',
    Delete_stream_note:
        'Обратите внимание, при удалении этого стрима сами посты удалены не будут. Вы можете удалить свои посты по их ссылкам.',
    Delete_stream: 'Вы уверены, что хотите удалить этот стрим? Это нельзя возвратить.',
    Delete: 'Удалить',
    Deleted: 'Удалено',
    Description: 'Описание',
    Develop: 'Разработка',
    'Developer Console': 'Консоль разработчика',
    Diff: 'Разница',
    Disconnect: 'Отсоедениться',
    Discussion: 'Обсуждения',
    Done: 'Сделано',
    'Down votes': 'Палец вниз',
    Downs: 'Палец вниз',
    Drag_drop: 'Скинуть картинку сюда',
    Drop: 'Скинуть',
    'E-mail': 'Е-майл',
    Edit_me: 'Изменить\u2026',
    'Edit your post below:': 'Поменять пост:',
    Edit: 'Изменить',
    'Embed on your site': 'Встроить в ваш сайт',
    Embed: 'Встроить',
    'Enter web link to your image': 'Добавить ссылку на картинку',
    'Enter web page to fetch': 'Введите веб-страницу для загрузки',
    Error: 'Ошибка',
    Explore: 'Искать',
    'Filter author posts': 'Показать посты хозяина',
    Filter: 'Фильтр',
    Finish: 'Сделано',
    first_post: 'Создать ваш первый пост.',
    Follow: 'Следить',
    Followers: 'Следят',
    Following: 'Слежу',
    Font: 'Шрифт',
    Fonts: 'Шрифты',
    'Forgot password': 'Забыли пароль',
    Forgot_password: 'Забыли пароль? Мы отправим вам е-майл для смены пароля.',
    'Fork this post': 'Копировать этот пост',
    Fork: 'Вилка',
    General: 'Основное',
    'Go to post': 'Перейти к посту',
    'Highest rated first': 'Самый популярный первый',
    'Highest rated': 'Высшее',
    History: 'История',
    'Hot first': 'Самый горячий первый',
    Hot: 'Горячее',
    hour: 'час',
    hours: 'часов',
    ID: 'Идентификация',
    Images: 'Картинки',
    in: 'в',
    In: 'В',
    Info: 'Инфо',
    Install: 'Установить',
    Joined: 'Присоединились',
    Karma: 'Карма',
    Language: 'Язык',
    'Latest first': 'Последний первый',
    Latest: 'Последнее',
    'Learn about bots': 'Узнать о ботах',
    'Learn more about anonymous posts': 'Узнать больше о анонимных постах',
    'Learn more': 'Подробнее',
    Less: 'Свернуть',
    'Link to image': 'Ссылка на картинку',
    'Link to video': 'Ссылка на видео',
    'Link to YouTube video': 'Ссылка на YouTube видео',
    Link: 'Ссылка',
    'Load more': 'Загрузить больше',
    Login: 'Войти',
    Logout: 'Выйти',
    'Manage bots': 'Управлять ботами',
    Manifest: 'Манифест',
    Mark_nudity:
        'Отметить этот контент как содержащий наготу, порнографию или другой неподабающий и откровенный контент.',
    'Markdown Help': 'Маркдаун Помощь',
    Markdown: 'Маркдаун',
    minute: 'минут',
    minutes: 'минут',
    Moderators: 'Модераторы',
    Modified: 'Изменено',
    month: 'месяц',
    months: 'месяцев',
    'More pictures': 'Больше картинок',
    'More streams': 'Больше стримов',
    more: 'больше',
    More: 'Развернуть',
    "My P's": 'Мои Посты',
    'My Posts': 'Мои Посты',
    'My streams': 'Мои стримы',
    'My Streams': 'Мои Стримы',
    Name: 'Имя',
    'New board': 'Новая коллекция',
    'New bot': 'Новый бот',
    'New Post': 'Новый Пост',
    'New post': 'Новый пост',
    No_bots: 'Не один бот пока не подсоединен.',
    no_posts_yet: 'Еще нет постов.',
    'Oldest first': 'Старый первый',
    Oldest: 'Старое',
    'Only you and moderators can post into this stream': 'Только вы и модераторы могут писать в этот стрим',
    Optional: 'Выборочно',
    'or drag image here': 'или скинуть картинку сюда',
    'P4 Components': 'P4 Компоненты',
    'P4 Product': 'P4 Продукт',
    Package: 'Пакет',
    Password: 'Пароль',
    'Paste image with': 'Вставить картинку с',
    Paste: 'Вставить',
    Permissions: 'Разрешения',
    'Pick a file': 'Выбрать файл\u2026',
    'Pick file from your hard drive': 'Выбрать файл с жесткого диска',
    'Picked streams': 'Выбранные стримы',
    'Post something': 'Начните писать',
    Post_anonymously: 'НЕ ХОТИТЕ ЛОГИНИТЬСЯ? ПОСТИТЕ АНОНИМНО',
    Post_count: 'Постов',
    Post_fork: 'Выберите стримы, на которые хотите разместить вилку',
    Post: 'Пост',
    Posts: 'Пост',
    Powered: 'Используя',
    Preview: 'Просмотр',
    'Privacy Policy': 'Политика конфиденциальности',
    Privacy: 'Конфиденциальность',
    Private: 'Личный',
    Profile: 'Профиль',
    Publish: 'Публиковать',
    Rating: 'Рейтинг',
    'Re-enter': 'Ввести повторно',
    'Read-only': 'Только для чтения',
    'Report abuse': 'Сообщить о нарушении',
    'Report Bugs': 'Сообщить об ошибках',
    'Report this post': 'Сообщить об этом посте',
    Report_post:
        'Сообщения о постах проверяются ежедневно, чтобы определить нарушают ли они наши Условия Пользования. Аккаунты, нарушающие наши Условия Пользования, могут быть удалены.',
    Report: 'Сообщить',
    'Reset password': 'Сбросить пароль',
    reset_code: 'Код был отправлен вам по е-майл, введите его здесь с новым паролем.',
    Saved: 'Сохранено',
    Search: 'Поиск',
    seconds: 'секунд',
    Security: 'Безопасность',
    'See more streams': 'Смотреть больше стримов',
    'Select default font style for your posts': 'Выбрать стиль шрифта для ваших постов',
    'Select Image': 'Вставить картинку',
    'Send e-mail': 'Послать е-майл',
    Send: 'Послать',
    Settings: 'Настройки',
    'Share on': 'Поделиться на',
    Share: 'Поделиться',
    'Short Link': 'Укороченная',
    'Short link': 'Укороченная',
    'Shorten Link': 'Укоротить Ссылку',
    'Sign up': 'Регистрация',
    Sign_with_pseudonym: 'Optionally, sign the post with pseudonym or avatar',
    Slug: 'Ссылка',
    Social: 'Соцсети',
    Sorting: 'Сортировка',
    Source: 'Источник',
    'Start posting right now': 'Начать писать',
    'Stream name': 'Название стрима',
    Stream: 'Стрим',
    Streams: 'Стримы',
    Styles: 'Стили',
    Submit: 'Отправить',
    Tags: 'Теги',
    'Terms of Use': 'Условия использования',
    terms: 'Условия',
    'This is your post': 'Это ваш пост',
    'This stream is private, only you and moderators can see it': 'Этот стрим личный, только вы и модераторы видят его',
    'This stream is public, anyone can see it': 'Этот стрим общедоступный, его все видят',
    Thumbnail: 'Картинка',
    Tip: 'Подсказка',
    Title: 'Заглавие',
    'Trending first': 'В топе первый',
    'Trending Posts': 'Топовые посты',
    Trending: 'В топе',
    try_again: 'Ошибка, попробовать еще раз.',
    'Type reply': 'Написать ответ',
    Unfollow: 'Отписаться',
    Unknown: 'Невидимка',
    Unnamed: 'Без имени',
    'Up votes': 'Палец вверх',
    Upload: 'Закачать',
    Ups: 'Палец вверх',
    User: 'Пользователь',
    Username: 'Ник',
    Videos: 'Видео',
    'View source': 'Посмотреть источник',
    View: 'Открыть',
    Views: 'Просмотры',
    Visit: 'Посетить',
    'Want to disconnect?': 'Хотите отсоединиться?',
    Webhooks: 'Вебхуки',
    Worst: 'Худшее',
    years: 'лет',
    'Your name': 'Ваше имя',
    'Your Streams': 'Мои Стримы',
};
