module.exports = {
    Italic: 'Курсив',
    text: 'текст',
    Bold: 'Жирный',
    Link: 'Ссылка',
    Highlighted: 'Выделенный',
    Strikethrough: 'Перечеркнутый',
    Underlined: 'Подчеркнутый',
    Super: 'Супер',
    Emoji: 'Эмоции',
    Inline: 'В тексте',
    tag: 'таг',
    Heading: 'Заголовок',
    Subheading: 'Подзаголовок',
    puss: 'кот',
    'This is a block quote': 'Это цитата',
    Item: 'Список',
    code: 'код',
    Bill: 'Дима',
    Bob: 'Вова',
    'Hello there': 'Всем привет',
    Thinking: 'Думает',
    Hello: 'Привет',
    BACK: 'НАЗАД',
    Blocks: 'Блоки',
    Text: 'Текст',
};
